import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.findClinics": "Find Clinics",
    "nav.staffDashboard": "Staff Dashboard",
    "nav.myAppointments": "My Appointments",
    "nav.healthAssistant": "Health Assistant",
    "nav.analytics": "Analytics",
    "nav.signOut": "Sign Out",
    "nav.login": "Login",
    "nav.signUp": "Sign Up",
    "nav.menu": "Menu",
    "nav.help": "Help & Support",
    "nav.restartTour": "Restart Tour",
    "nav.consultants": "Consultants",
    
    // Featured Consultants
    "featuredConsultants.badge": "Wellness Advisors",
    "featuredConsultants.title": "Need Guidance? Meet Our Wellness Advisors",
    "featuredConsultants.subtitle": "Not sure which clinic to choose? Our trusted advisors help guide you to the right healthcare providers.",
    "featuredConsultants.viewAll": "View All Advisors",
    
    // Hero
    "hero.badge": "Queue • Book • Connect",
    "hero.title1": "Healthcare Made",
    "hero.title2": "Simple & Smart",
    "hero.subtitle": "Join virtual queues, book appointments instantly, and connect with healthcare professionals across Singapore",
    "hero.findClinics": "Find Clinics",
    "hero.learnMore": "Learn More",
    "hero.queueTitle": "Queue",
    "hero.queueDesc": "Real-time virtual queues & wait times",
    "hero.bookTitle": "Book",
    "hero.bookDesc": "Instant appointments across all clinics",
    "hero.connectTitle": "Connect",
    "hero.connectDesc": "AI health assistant & support",
    
    // Features
    "features.badge": "Features",
    "features.title": "Digital Queue • Book • Connect",
    "features.subtitle": "A complete healthcare platform designed for Singapore's diverse medical ecosystem",
    "features.queue.title": "Digital Queue",
    "features.queue.subtitle": "Real-time Updates",
    "features.queue.description": "Join virtual queues from anywhere and see live queue status and wait times before you go.",
    "features.book.title": "Book",
    "features.book.subtitle": "Easy Appointments",
    "features.book.description": "Book appointments across GP, TCM, and wellness centers with instant confirmation.",
    "features.connect.title": "Connect",
    "features.connect.subtitle": "Smart Assistance",
    "features.connect.description": "Pre and post consultation support via AI-powered health chatbot assistance.",
    "features.transparency.title": "Doctor Transparency",
    "features.transparency.description": "View profiles, specialties, and patient reviews",
    "features.pdpa.title": "PDPA Compliant",
    "features.pdpa.description": "Your data is secure and privacy-protected",
    "features.fast.title": "Fast & Efficient",
    "features.fast.description": "Reduce waiting time and streamline your healthcare journey",
    
    // Queue Page
    "queue.title": "Live Queue",
    "queue.loading": "Loading queue information...",
    "queue.inQueue": "In Queue",
    "queue.estWait": "Est. Wait",
    "queue.enableNotifications": "Enable notifications for queue updates",
    "queue.notificationDesc": "Get notified when it's almost your turn so you don't miss your spot",
    "queue.complete": "Consultation Complete!",
    "queue.thankYou": "Thank you for visiting",
    "queue.rateVisit": "Rate your visit",
    "queue.feedbackThanks": "Thanks for your feedback!",
    "queue.feedbackHelps": "Your feedback helps us improve our service",
    "queue.returnHome": "Return to Home",
    "queue.bookAgain": "Book Again",
    "queue.beingServedNow": "You're Being Served Now!",
    "queue.proceedToConsultation": "Please proceed to the consultation area",
    "queue.yourQueueNumber": "Your Queue Number",
    "queue.checkedIn": "You're in Queue!",
    "queue.updated": "Updated",
    "queue.ago": "ago",
    "queue.queueNumber": "Queue Number",
    "queue.status": "Status",
    "queue.waiting": "Waiting",
    "queue.estWaitTime": "Est. Wait",
    "queue.visitType": "Visit Type",
    "queue.peopleAhead": "People Ahead",
    "queue.generalConsultation": "General Consultation",
    "queue.notifiedWhenTurn": "You'll be notified when it's your turn",
    "queue.leaveQueue": "Leave Queue",
    "queue.checkIn": "Check In",
    "queue.joinQueue": "Join Queue",
    "queue.notificationsOn": "Notifications On",
    "queue.enableAlerts": "Enable Alerts",
    "queue.minutes": "min",
    "queue.disclaimer.title": "Before Joining the Queue",
    "queue.disclaimer.riskAssessment": "Please arrive 10 minutes early for risk assessment. Urgent cases may override queue sequence based on clinic priority rules.",
    "queue.disclaimer.queueShift": "Your queue position may change if urgent walk-in patients arrive.",
    "queue.disclaimer.understand": "I understand and agree",
    "queue.queueShiftNotice": "Queue updated by clinic. Your position has changed based on clinic priority rules.",
    "queue.preConsult.title": "Pre-Consultation Information",
    "queue.preConsult.visitReason": "Reason for Visit",
    "queue.preConsult.visitReasonPlaceholder": "Please describe your symptoms or reason for visit...",
    "queue.preConsult.visitType": "Visit Type",
    "queue.preConsult.continue": "Continue to Queue",
    "queue.smsConfirmation": "SMS confirmation sent with re-queue link",
    
    // Staff Dashboard
    "staff.title": "Staff Dashboard",
    "staff.loading": "Loading staff dashboard...",
    "staff.queueStatus": "Queue Status:",
    "staff.open": "Open",
    "staff.closed": "Closed",
    "staff.totalToday": "Total Today",
    "staff.waiting": "Waiting",
    "staff.served": "Served",
    "staff.avgWait": "Avg Wait",
    "staff.currentQueue": "Current Queue",
    "staff.managePatients": "Manage patients waiting in line",
    "staff.callNextPatient": "Call Next Patient",
    "staff.noPatients": "No patients in queue",
    "staff.queueEmpty": "Queue is empty right now",
    "staff.patient": "Patient",
    "staff.waitingTime": "Waiting:",
    "staff.minutes2": "minutes",
    "staff.callPatient": "Call Patient",
    "staff.markServed": "Mark Served",
    "staff.cancel": "Cancel",
    "staff.noShow": "No-Show",
    "staff.moveUp": "Move up",
    "staff.moveDown": "Move down",
    "staff.addWalkIn": "Add Walk-In Patient",
    "staff.walkInName": "Patient Name",
    "staff.walkInPhone": "Phone Number",
    "staff.walkInNamePlaceholder": "Enter patient name",
    "staff.walkInPhonePlaceholder": "+65 XXXX XXXX",
    "staff.walkInAdded": "Walk-in patient added to queue",
    
    // Footer
    "footer.tagline": "Simplifying healthcare access across Singapore",
    "footer.forPatients": "For Patients",
    "footer.findClinics": "Find Clinics",
    "footer.howItWorks": "How it Works",
    "footer.faq": "FAQ",
    "footer.forClinics": "For Clinics",
    "footer.joinPlatform": "Join Platform",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.company": "Company",
    "footer.aboutUs": "About Us",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.copyright": "© 2024 ClynicQ. PDPA Compliant Healthcare Platform.",
    
    // Appointments Page
    "appointments.title": "My Appointments",
    "appointments.bookNew": "Book New Appointment",
    "appointments.reason": "Reason",
    "appointments.noAppointments": "No appointments yet",
    "appointments.browseClinics": "Browse Clinics",
    "appointments.loading": "Loading...",
    "appointments.failedToLoad": "Failed to load appointments",
    "appointments.signInRequired": "Please sign in to view appointments",
    
    // Analytics Page
    "analytics.title": "Analytics Dashboard",
    "analytics.phase4": "Phase 4 - Data Insights",
    "analytics.overview": "Last 30 days overview",
    "analytics.operationalTrends": "Operational Trends",
    "analytics.totalPatients": "Total Patients",
    "analytics.queueEntries": "Queue entries",
    "analytics.avgWaitTime": "Avg Wait Time",
    "analytics.perPatient": "Per patient",
    "analytics.appointments": "Appointments",
    "analytics.booked": "Booked",
    "analytics.noShowRate": "No-Show Rate",
    "analytics.noShows": "no-shows",
    "analytics.behaviorSignals": "Patient Behavior Signals",
    "analytics.bookingPatterns": "Booking Patterns",
    "analytics.bookingQuestion": "How far in advance do patients book?",
    "analytics.avgBookingWindow": "Average Booking Window",
    "analytics.days": "days",
    "analytics.returnPatientRate": "Return Patient Rate",
    "analytics.peakActivity": "Peak Activity",
    "analytics.commonPatterns": "Most common booking patterns",
    "analytics.patients": "patients",
    "analytics.performanceBenchmark": "Performance Benchmarking",
    "analytics.comparePerformance": "Compare your clinic's performance over time",
    "analytics.queueEfficiency": "Queue Efficiency",
    "analytics.waitTimeVsStandard": "Average wait time vs industry standard",
    "analytics.excellent": "Excellent",
    "analytics.needsImprovement": "Needs Improvement",
    "analytics.patientRetention": "Patient Retention",
    "analytics.returnRateVsAverage": "Return patient rate vs industry average",
    "analytics.aboveAverage": "Above Average",
    "analytics.average": "Average",
    "analytics.attendanceRate": "Attendance Rate",
    "analytics.noShowVsBenchmark": "No-show rate vs industry benchmark",
    "analytics.needsAttention": "Needs Attention",
    "analytics.loadingAnalytics": "Loading analytics...",
    "analytics.accessDenied": "Access denied. Only clinic staff can view analytics.",
    
    // Booking Page
    "booking.title": "Book Appointment",
    "booking.selectDoctor": "Select Doctor (Optional)",
    "booking.anyDoctor": "Any available doctor",
    "booking.selectDate": "Select Date",
    "booking.selectTime": "Select Time",
    "booking.reasonForVisit": "Reason for Visit",
    "booking.reasonPlaceholder": "Brief description of your symptoms or reason for visit...",
    "booking.cancel": "Cancel",
    "booking.confirmBooking": "Confirm Booking",
    "booking.booking": "Booking...",
    "booking.signInRequired": "Please sign in to book an appointment",
    "booking.selectDateTime": "Please select both date and time",
    "booking.bookingSuccess": "Appointment booked successfully!",
    "booking.failedToLoad": "Failed to load clinic information",
    "booking.bookingFailed": "Failed to book appointment",
    "booking.loading": "Loading...",
    
    // Chatbot Page
    "chatbot.title": "Health Assistant",
    "chatbot.subtitle": "Ask me anything about your health",
    "chatbot.placeholder": "Type your message...",
    "chatbot.disclaimer": "This is an AI assistant. Always consult with healthcare professionals for medical advice.",
    "chatbot.welcome": "Hello! I'm your ClynicQ health assistant. I can help you with:\n\n• Symptom assessment\n• Health advice\n• Appointment preparation\n• Post-consultation care\n\nHow can I assist you today?",
    "chatbot.errorMessage": "I'm sorry, I encountered an error. Please try again.",
    "chatbot.failedToSend": "Failed to send message",
    
    // Dashboard Page
    "dashboard.title": "Clinic Dashboard",
    "dashboard.todayAppointments": "Today's Appointments",
    "dashboard.inQueue": "In Queue",
    "dashboard.pendingApproval": "Pending Approval",
    "dashboard.totalUpcoming": "Total Upcoming",
    "dashboard.appointments": "Appointments",
    "dashboard.queue": "Queue",
    "dashboard.plugins": "Plugins",
    "dashboard.confirm": "Confirm",
    "dashboard.decline": "Decline",
    "dashboard.noUpcoming": "No upcoming appointments",
    "dashboard.noOneInQueue": "No one in queue",
    "dashboard.loading": "Loading...",
    "dashboard.accessDenied": "You don't have access to the dashboard",
    "dashboard.noClinic": "No clinic assigned to your account",
    "dashboard.failedToLoad": "Failed to load dashboard data",
    "dashboard.confirmed": "confirmed",
    "dashboard.cancelled": "cancelled",
    "dashboard.estWait": "Est. wait",
    "dashboard.walkIn": "Walk-in Patient",
    
    // Auth Page
    "auth.welcomeBack": "Welcome Back",
    "auth.enterCredentials": "Enter your credentials to access your account",
    "auth.createAccount": "Create Account",
    "auth.signupDescription": "Sign up to start booking appointments",
    "auth.email": "Email",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "Password",
    "auth.fullName": "Full Name",
    "auth.namePlaceholder": "John Doe",
    "auth.confirmPassword": "Confirm Password",
    "auth.signIn": "Sign In",
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.termsAgreement": "By continuing, you agree to our Terms of Service and Privacy Policy",
    "auth.invalidEmail": "Invalid email address",
    "auth.passwordLength": "Password must be at least 6 characters",
    "auth.passwordMismatch": "Passwords don't match",
    "auth.nameTooShort": "Name must be at least 2 characters",
    
    // NotFound Page
    "notFound.title": "404",
    "notFound.message": "Oops! Page not found",
    "notFound.returnHome": "Return to Home",
    
    // ClinicCard
    "clinicCard.open": "Open",
    "clinicCard.closed": "Closed",
    "clinicCard.inQueue": "In Queue",
    "clinicCard.people": "people",
    "clinicCard.estWait": "Est. Wait",
    "clinicCard.youreInQueue": "You're in the Queue",
    "clinicCard.position": "Position",
    "clinicCard.of": "of",
    "clinicCard.waiting": "Waiting",
    "clinicCard.checkIn": "Check In",
    "clinicCard.leaveQueue": "Leave Queue",
    "clinicCard.readyToSkip": "Ready to Skip the Wait?",
    "clinicCard.joinVirtual": "Join the virtual queue now",
    "clinicCard.visitType": "Visit Type",
    "clinicCard.generalConsultation": "General Consultation",
    "clinicCard.followUp": "Follow-up",
    "clinicCard.emergency": "Emergency",
    "clinicCard.vaccination": "Vaccination",
    "clinicCard.healthScreening": "Health Screening",
    "clinicCard.joinQueue": "Join Queue",
    "clinicCard.joining": "Joining...",
    "clinicCard.viewDetails": "View Details",
    "clinicCard.queueSuccess": "You're #{number} in the queue!",
    "clinicCard.alreadyInQueue": "You're already in this queue!",
    "clinicCard.leftQueue": "Left the queue successfully",
    "clinicCard.failedToLeave": "Failed to leave queue",
    "clinicCard.checkedIn": "Checked in successfully!",
    "clinicCard.signInRequired": "Please sign in to join the queue",
    "clinicCard.failedToJoin": "Failed to join queue",
    "clinicCard.availabilitiesToday": "Availabilities Today",
    "clinicCard.servicesOffered": "Services Offered",
    "clinicCard.joinedQueue": "You've joined the queue!",
    
    // MarketplaceSection
    "marketplace.title": "Find Your Clinic",
    "marketplace.subtitle": "Browse clinics near you with real-time queue information and join virtual queues instantly",
    "marketplace.loading": "Loading clinics...",
    
    // SearchFilters
    "search.placeholder": "Search clinics, doctors, or specialties...",
    "search.location": "Location",
    "search.filters": "Filters",
    "search.all": "All",
    "search.gp": "GP",
    "search.tcm": "TCM",
    "search.wellness": "Wellness",
    "search.specialists": "Specialists",
    
    // QuickGuide
    "guide.welcome": "Welcome to ClynicQ! 👋",
    "guide.description": "Your digital healthcare companion. Queue, Book, and Connect with healthcare services across Singapore.",
    "guide.quickLinks": "Quick Links:",
    "guide.joinQueue": "Join Queue",
    "guide.appointments": "Appointments",
    "guide.healthAssistant": "Health Assistant",
    "guide.analytics": "Analytics",
    "guide.minimize": "Minimize",
    "guide.gotIt": "Got it!",
    "guide.quickGuide": "Quick Guide",
    
    // OnboardingTour
    "tour.welcomeTitle": "Welcome to ClynicQ! 👋",
    "tour.welcomeDesc": "Queue • Book • Connect with healthcare services. The 'Q' badge shows active queues on selected clinics.",
    "tour.browseTitle": "Browse & Join Queues 🏥",
    "tour.browseDesc": "Find clinics, check real-time queues, and join virtually from anywhere.",
    "tour.navTitle": "Quick Access 🧭",
    "tour.navDesc": "Use the menu to access appointments, health assistant, and analytics.",
    "tour.back": "Back",
    "tour.skip": "Skip",
    "tour.next": "Next",
    "tour.gotIt": "Got it!",
    "tour.stepCount": "{current} of {total}",
    
    // MyClynicQPlugin
    "myclynicq.comingSoon": "Coming Soon",
    "myclynicq.title": "MyClynicQ",
    "myclynicq.subtitle": "Never miss an appointment with automated reminders and instant support on WhatsApp",
    "myclynicq.chatWhatsApp": "Chat on WhatsApp",
    "myclynicq.alwaysAvailable": "Your health assistant, always available",
    "myclynicq.easyBooking": "Easy Booking",
    "myclynicq.easyBookingDesc": "Book, reschedule, or cancel appointments via chat",
    "myclynicq.smartReminders": "Smart Reminders",
    "myclynicq.smartRemindersDesc": "Get timely reminders so you never miss a visit",
    "myclynicq.instantAnswers": "Instant Answers",
    "myclynicq.instantAnswersDesc": "Ask questions about your appointment or clinic anytime",
    "myclynicq.queueUpdates": "Queue Updates",
    "myclynicq.queueUpdatesDesc": "Know your queue position without calling the clinic",
    "myclynicq.howItWorks": "How It Works",
    "myclynicq.step1": "Book an appointment on ClynicQ",
    "myclynicq.step2": "Get a confirmation message on WhatsApp",
    "myclynicq.step3": "Receive reminders before your visit",
    "myclynicq.step4": "Chat with MyClynicQ anytime for help",
    "myclynicq.availableChannels": "Available Channels",
    "myclynicq.whatsapp": "WhatsApp",
    "myclynicq.sms": "SMS",
    "myclynicq.webChat": "Web Chat",
    "myclynicq.stayConnected": "Stay connected with your healthcare journey. MyClynicQ keeps you informed and makes managing appointments effortless.",
    
    // DoctorProfile
    "doctorProfile.loading": "Loading doctor profile...",
    "doctorProfile.notFound": "Doctor not found",
    "doctorProfile.qualifications": "Qualifications",
    "doctorProfile.languages": "Languages",
    "doctorProfile.about": "About",
    "doctorProfile.availability": "Availability",
    "doctorProfile.bookAppointment": "Book Appointment",
    "doctorProfile.viewClinic": "View Clinic",
    "doctorProfile.registration": "Reg",
    "doctorProfile.yearsExperience": "years experience",
    "doctorProfile.noQualifications": "No qualifications listed",
    "doctorProfile.noLanguages": "No languages listed",
    "doctorProfile.closed": "Closed",
    
    // ClinicProfile
    "clinicProfile.bookAppointment": "Book Appointment",
    "clinicProfile.joinQueue": "Join Queue",
    "clinicProfile.clinicPhotos": "Clinic Photos",
    "clinicProfile.photoGalleryComingSoon": "Photo gallery coming soon",
    "clinicProfile.phone": "Phone",
    "clinicProfile.email": "Email",
    "clinicProfile.notAvailable": "Not available",
    "clinicProfile.currentQueue": "Current Queue",
    "clinicProfile.waiting": "waiting",
    "clinicProfile.doctors": "Doctors",
    "clinicProfile.awards": "Awards",
    "clinicProfile.operatingHours": "Operating Hours",
    "clinicProfile.reviews": "Reviews",
    "clinicProfile.verified": "Verified",
    "clinicProfile.yearsExperience": "years experience",
    "clinicProfile.qualifications": "Qualifications & Certificates",
    "clinicProfile.noDoctorsAvailable": "No doctors information available",
    "clinicProfile.awardsRecognition": "Awards & Recognition",
    "clinicProfile.awardedIn": "Awarded in",
    "clinicProfile.awardsComingSoon": "Awards and recognition will be displayed here",
    "clinicProfile.noReviews": "No reviews yet",
    "clinicProfile.anonymous": "Anonymous",
    "clinicProfile.loading": "Loading...",
    "clinicProfile.signInToBook": "Please sign in to book an appointment",
    "clinicProfile.failedToLoad": "Failed to load clinic information",
    
    // Consultant Section
    "consultant.badge": "Expert Guidance",
    "consultant.pageTitle": "Wellness Advisors",
    "consultant.pageDescription": "Not sure which clinic to choose? Our trusted wellness advisors guide you to the right healthcare provider.",
    "consultant.searchPlaceholder": "Search by name or specialty...",
    "consultant.feature1Title": "Personalized Guidance",
    "consultant.feature1Desc": "Get matched to the right provider",
    "consultant.feature2Title": "Trusted Experts",
    "consultant.feature2Desc": "Verified healthcare professionals",
    "consultant.feature3Title": "Free Consultation",
    "consultant.feature3Desc": "No obligation, no pressure",
    "consultant.noResults": "No consultants found",
    "consultant.noResultsDesc": "Try adjusting your search criteria",
    "consultant.viewProfile": "View Profile",
    "consultant.notFound": "Consultant not found",
    "consultant.backToList": "Back to Consultants",
    "consultant.getGuidance": "Get Guidance",
    "consultant.about": "About",
    "consultant.services": "Services Offered",
    "consultant.patientTypes": "Types of Patients",
    "consultant.needHelp": "Need Help Deciding?",
    "consultant.needHelpDesc": "Speak directly with this advisor for personalized recommendations.",
    "consultant.speakToConsultant": "Speak to Consultant",
    "consultant.recommendedClinics": "Recommended Clinics",
    "consultant.recommendedBy": "Recommended by {name}",
    
    // Admin Consultants
    "admin.consultantsTitle": "Manage Consultants",
    "admin.consultantsDesc": "Add, edit, and manage wellness advisors",
    "admin.addConsultant": "Add Consultant",
    "admin.editConsultant": "Edit Consultant",
    "admin.name": "Name",
    "admin.namePlaceholder": "Enter consultant name",
    "admin.title": "Title",
    "admin.titlePlaceholder": "e.g. Wellness Advisor",
    "admin.photoUrl": "Photo URL",
    "admin.shortBio": "Short Bio",
    "admin.shortBioPlaceholder": "Brief description (2-3 lines)",
    "admin.fullBio": "Full Bio",
    "admin.fullBioPlaceholder": "Detailed background and experience",
    "admin.areasOfFocus": "Areas of Focus",
    "admin.addAreaPlaceholder": "e.g. Pain Management",
    "admin.servicesOffered": "Services Offered",
    "admin.addServicePlaceholder": "e.g. Health Assessment",
    "admin.patientTypes": "Patient Types",
    "admin.addPatientTypePlaceholder": "e.g. Chronic Pain Patients",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.update": "Update",
    "admin.create": "Create",
    "admin.recommendedClinics": "Recommended Clinics",
    "admin.addClinic": "Add Clinic",
    "admin.noConsultants": "No consultants yet",
    "admin.noConsultantsDesc": "Add your first wellness advisor to get started",
    "admin.nameRequired": "Name is required",
    "admin.updateError": "Failed to update consultant",
    "admin.createError": "Failed to create consultant",
    "admin.consultantUpdated": "Consultant updated successfully",
    "admin.consultantCreated": "Consultant created successfully",
  },
  zh: {
    // Navbar
    "nav.findClinics": "寻找诊所",
    "nav.staffDashboard": "员工仪表板",
    "nav.myAppointments": "我的预约",
    "nav.healthAssistant": "健康助手",
    "nav.analytics": "分析",
    "nav.signOut": "登出",
    "nav.login": "登录",
    "nav.signUp": "注册",
    "nav.menu": "菜单",
    "nav.help": "帮助与支持",
    "nav.restartTour": "重新开始导览",
    "nav.consultants": "健康顾问",
    
    // Featured Consultants
    "featuredConsultants.badge": "健康顾问",
    "featuredConsultants.title": "需要指导？认识我们的健康顾问",
    "featuredConsultants.subtitle": "不确定选择哪家诊所？我们值得信赖的顾问帮助您找到合适的医疗服务提供者。",
    "featuredConsultants.viewAll": "查看所有顾问",
    
    // Hero
    "hero.badge": "排队 • 预约 • 连接",
    "hero.title1": "简单智能的",
    "hero.title2": "医疗保健",
    "hero.subtitle": "随时随地加入虚拟队列、即时预约，并与新加坡各地的医疗保健专业人员联系",
    "hero.findClinics": "寻找诊所",
    "hero.learnMore": "了解更多",
    "hero.queueTitle": "排队",
    "hero.queueDesc": "实时虚拟队列和等待时间",
    "hero.bookTitle": "预约",
    "hero.bookDesc": "所有诊所的即时预约",
    "hero.connectTitle": "连接",
    "hero.connectDesc": "AI健康助手和支持",
    
    // Features
    "features.badge": "功能特色",
    "features.title": "数字排队 • 预约 • 连接",
    "features.subtitle": "为新加坡多元化医疗生态系统设计的完整医疗保健平台",
    "features.queue.title": "数字排队",
    "features.queue.subtitle": "实时更新",
    "features.queue.description": "随时随地加入虚拟队列，在出发前查看实时队列状态和等待时间。",
    "features.book.title": "预约",
    "features.book.subtitle": "轻松预约",
    "features.book.description": "在全科、中医和健康中心预约，即时确认。",
    "features.connect.title": "连接",
    "features.connect.subtitle": "智能协助",
    "features.connect.description": "通过AI驱动的健康聊天机器人提供咨询前后的支持。",
    "features.transparency.title": "医生透明度",
    "features.transparency.description": "查看简介、专长和患者评价",
    "features.pdpa.title": "符合PDPA",
    "features.pdpa.description": "您的数据安全且受隐私保护",
    "features.fast.title": "快速高效",
    "features.fast.description": "减少等待时间，简化您的医疗保健旅程",
    
    // Queue Page
    "queue.title": "实时队列",
    "queue.loading": "加载队列信息中...",
    "queue.inQueue": "队列中",
    "queue.estWait": "预计等待",
    "queue.enableNotifications": "启用队列更新通知",
    "queue.notificationDesc": "在轮到您时收到通知，不会错过您的位置",
    "queue.complete": "咨询完成！",
    "queue.thankYou": "感谢您的光临",
    "queue.rateVisit": "评价您的就诊",
    "queue.feedbackThanks": "感谢您的反馈！",
    "queue.feedbackHelps": "您的反馈帮助我们改进服务",
    "queue.returnHome": "返回首页",
    "queue.bookAgain": "再次预约",
    "queue.beingServedNow": "正在为您服务！",
    "queue.proceedToConsultation": "请前往咨询区",
    "queue.yourQueueNumber": "您的队列号码",
    "queue.checkedIn": "您在队列中！",
    "queue.updated": "更新于",
    "queue.ago": "前",
    "queue.queueNumber": "队列号码",
    "queue.status": "状态",
    "queue.waiting": "等待中",
    "queue.estWaitTime": "预计等待",
    "queue.visitType": "就诊类型",
    "queue.peopleAhead": "前面的人数",
    "queue.generalConsultation": "一般咨询",
    "queue.notifiedWhenTurn": "轮到您时会收到通知",
    "queue.leaveQueue": "离开队列",
    "queue.checkIn": "签到",
    "queue.joinQueue": "加入队列",
    "queue.notificationsOn": "通知已开启",
    "queue.enableAlerts": "启用提醒",
    "queue.minutes": "分钟",
    "queue.disclaimer.title": "加入队列前",
    "queue.disclaimer.riskAssessment": "请提前10分钟到达进行风险评估。紧急情况可能会根据诊所优先规则覆盖队列顺序。",
    "queue.disclaimer.queueShift": "如果有紧急上门患者到达，您的队列位置可能会改变。",
    "queue.disclaimer.understand": "我理解并同意",
    "queue.queueShiftNotice": "诊所已更新队列。您的位置已根据诊所优先规则更改。",
    "queue.preConsult.title": "咨询前信息",
    "queue.preConsult.visitReason": "就诊原因",
    "queue.preConsult.visitReasonPlaceholder": "请描述您的症状或就诊原因...",
    "queue.preConsult.visitType": "就诊类型",
    "queue.preConsult.continue": "继续排队",
    "queue.smsConfirmation": "已发送包含重新排队链接的短信确认",
    
    // Staff Dashboard
    "staff.title": "员工仪表板",
    "staff.loading": "加载员工仪表板中...",
    "staff.queueStatus": "队列状态：",
    "staff.open": "开放",
    "staff.closed": "关闭",
    "staff.totalToday": "今日总数",
    "staff.waiting": "等待中",
    "staff.served": "已服务",
    "staff.avgWait": "平均等待",
    "staff.currentQueue": "当前队列",
    "staff.managePatients": "管理排队等候的患者",
    "staff.callNextPatient": "呼叫下一位患者",
    "staff.noPatients": "队列中没有患者",
    "staff.queueEmpty": "队列目前为空",
    "staff.patient": "患者",
    "staff.waitingTime": "等待：",
    "staff.minutes2": "分钟",
    "staff.callPatient": "呼叫患者",
    "staff.markServed": "标记已服务",
    "staff.cancel": "取消",
    "staff.noShow": "未出现",
    "staff.moveUp": "上移",
    "staff.moveDown": "下移",
    "staff.addWalkIn": "添加上门患者",
    "staff.walkInName": "患者姓名",
    "staff.walkInPhone": "电话号码",
    "staff.walkInNamePlaceholder": "输入患者姓名",
    "staff.walkInPhonePlaceholder": "+65 XXXX XXXX",
    "staff.walkInAdded": "上门患者已添加到队列",
    
    // Footer
    "footer.tagline": "简化新加坡的医疗保健服务",
    "footer.forPatients": "患者服务",
    "footer.findClinics": "寻找诊所",
    "footer.howItWorks": "工作原理",
    "footer.faq": "常见问题",
    "footer.forClinics": "诊所服务",
    "footer.joinPlatform": "加入平台",
    "footer.features": "功能特色",
    "footer.pricing": "价格",
    "footer.company": "公司",
    "footer.aboutUs": "关于我们",
    "footer.privacyPolicy": "隐私政策",
    "footer.termsOfService": "服务条款",
    "footer.copyright": "© 2024 ClynicQ. 符合PDPA的医疗保健平台。",
    
    // Appointments Page
    "appointments.title": "我的预约",
    "appointments.bookNew": "预约新时段",
    "appointments.reason": "原因",
    "appointments.noAppointments": "暂无预约",
    "appointments.browseClinics": "浏览诊所",
    "appointments.loading": "加载中...",
    "appointments.failedToLoad": "加载预约失败",
    "appointments.signInRequired": "请登录以查看预约",
    
    // Analytics Page
    "analytics.title": "分析仪表板",
    "analytics.phase4": "阶段4 - 数据洞察",
    "analytics.overview": "最近30天概览",
    "analytics.operationalTrends": "运营趋势",
    "analytics.totalPatients": "总患者数",
    "analytics.queueEntries": "队列记录",
    "analytics.avgWaitTime": "平均等待时间",
    "analytics.perPatient": "每位患者",
    "analytics.appointments": "预约",
    "analytics.booked": "已预约",
    "analytics.noShowRate": "未出现率",
    "analytics.noShows": "未出现",
    "analytics.behaviorSignals": "患者行为信号",
    "analytics.bookingPatterns": "预约模式",
    "analytics.bookingQuestion": "患者提前多久预约？",
    "analytics.avgBookingWindow": "平均预约窗口",
    "analytics.days": "天",
    "analytics.returnPatientRate": "回访患者率",
    "analytics.peakActivity": "高峰活动",
    "analytics.commonPatterns": "最常见的预约模式",
    "analytics.patients": "患者",
    "analytics.performanceBenchmark": "绩效基准",
    "analytics.comparePerformance": "比较您诊所的表现随时间的变化",
    "analytics.queueEfficiency": "队列效率",
    "analytics.waitTimeVsStandard": "平均等待时间与行业标准",
    "analytics.excellent": "优秀",
    "analytics.needsImprovement": "需要改进",
    "analytics.patientRetention": "患者保留",
    "analytics.returnRateVsAverage": "回访患者率与行业平均",
    "analytics.aboveAverage": "高于平均",
    "analytics.average": "平均",
    "analytics.attendanceRate": "出勤率",
    "analytics.noShowVsBenchmark": "未出现率与行业基准",
    "analytics.needsAttention": "需要关注",
    "analytics.loadingAnalytics": "加载分析中...",
    "analytics.accessDenied": "拒绝访问。仅诊所员工可查看分析。",
    
    // Booking Page
    "booking.title": "预约",
    "booking.selectDoctor": "选择医生（可选）",
    "booking.anyDoctor": "任何可用的医生",
    "booking.selectDate": "选择日期",
    "booking.selectTime": "选择时间",
    "booking.reasonForVisit": "就诊原因",
    "booking.reasonPlaceholder": "简要描述您的症状或就诊原因...",
    "booking.cancel": "取消",
    "booking.confirmBooking": "确认预约",
    "booking.booking": "预约中...",
    "booking.signInRequired": "请登录以预约",
    "booking.selectDateTime": "请选择日期和时间",
    "booking.bookingSuccess": "预约成功！",
    "booking.failedToLoad": "加载诊所信息失败",
    "booking.bookingFailed": "预约失败",
    "booking.loading": "加载中...",
    
    // Chatbot Page
    "chatbot.title": "健康助手",
    "chatbot.subtitle": "问我任何关于您健康的问题",
    "chatbot.placeholder": "输入您的消息...",
    "chatbot.disclaimer": "这是一个AI助手。请始终咨询医疗保健专业人员以获取医疗建议。",
    "chatbot.welcome": "您好！我是您的ClynicQ健康助手。我可以帮助您：\n\n• 症状评估\n• 健康建议\n• 预约准备\n• 咨询后护理\n\n我今天能为您提供什么帮助？",
    "chatbot.errorMessage": "抱歉，我遇到了错误。请重试。",
    "chatbot.failedToSend": "发送消息失败",
    
    // Dashboard Page
    "dashboard.title": "诊所仪表板",
    "dashboard.todayAppointments": "今日预约",
    "dashboard.inQueue": "队列中",
    "dashboard.pendingApproval": "待批准",
    "dashboard.totalUpcoming": "即将到来的总数",
    "dashboard.appointments": "预约",
    "dashboard.queue": "队列",
    "dashboard.plugins": "插件",
    "dashboard.confirm": "确认",
    "dashboard.decline": "拒绝",
    "dashboard.noUpcoming": "无即将到来的预约",
    "dashboard.noOneInQueue": "队列中无人",
    "dashboard.loading": "加载中...",
    "dashboard.accessDenied": "您无权访问仪表板",
    "dashboard.noClinic": "您的账户未分配诊所",
    "dashboard.failedToLoad": "加载仪表板数据失败",
    "dashboard.confirmed": "已确认",
    "dashboard.cancelled": "已取消",
    "dashboard.estWait": "预计等待",
    "dashboard.walkIn": "步入患者",
    
    // Auth Page
    "auth.welcomeBack": "欢迎回来",
    "auth.enterCredentials": "输入您的凭据以访问您的账户",
    "auth.createAccount": "创建账户",
    "auth.signupDescription": "注册以开始预约",
    "auth.email": "邮箱",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "密码",
    "auth.fullName": "全名",
    "auth.namePlaceholder": "张三",
    "auth.confirmPassword": "确认密码",
    "auth.signIn": "登录",
    "auth.login": "登录",
    "auth.signup": "注册",
    "auth.termsAgreement": "继续即表示您同意我们的服务条款和隐私政策",
    "auth.invalidEmail": "无效的邮箱地址",
    "auth.passwordLength": "密码必须至少6个字符",
    "auth.passwordMismatch": "密码不匹配",
    "auth.nameTooShort": "姓名必须至少2个字符",
    
    // NotFound Page
    "notFound.title": "404",
    "notFound.message": "哎呀！页面未找到",
    "notFound.returnHome": "返回主页",
    
    // ClinicCard
    "clinicCard.open": "开放",
    "clinicCard.closed": "关闭",
    "clinicCard.inQueue": "队列中",
    "clinicCard.people": "人",
    "clinicCard.estWait": "预计等待",
    "clinicCard.youreInQueue": "您在队列中",
    "clinicCard.position": "位置",
    "clinicCard.of": "共",
    "clinicCard.waiting": "等待中",
    "clinicCard.checkIn": "签到",
    "clinicCard.leaveQueue": "离开队列",
    "clinicCard.readyToSkip": "准备跳过等待？",
    "clinicCard.joinVirtual": "立即加入虚拟队列",
    "clinicCard.visitType": "就诊类型",
    "clinicCard.generalConsultation": "一般咨询",
    "clinicCard.followUp": "复诊",
    "clinicCard.emergency": "急诊",
    "clinicCard.vaccination": "疫苗接种",
    "clinicCard.healthScreening": "健康检查",
    "clinicCard.joinQueue": "加入队列",
    "clinicCard.joining": "加入中...",
    "clinicCard.viewDetails": "查看详情",
    "clinicCard.queueSuccess": "您是队列中的第{number}号！",
    "clinicCard.alreadyInQueue": "您已在此队列中！",
    "clinicCard.leftQueue": "成功离开队列",
    "clinicCard.failedToLeave": "离开队列失败",
    "clinicCard.checkedIn": "签到成功！",
    "clinicCard.signInRequired": "请登录以加入队列",
    "clinicCard.failedToJoin": "加入队列失败",
    "clinicCard.availabilitiesToday": "今日可预约时段",
    "clinicCard.servicesOffered": "提供的服务",
    "clinicCard.joinedQueue": "您已加入队列！",
    
    // MarketplaceSection
    "marketplace.title": "寻找您的诊所",
    "marketplace.subtitle": "浏览附近的诊所，查看实时队列信息并立即加入虚拟队列",
    "marketplace.loading": "加载诊所中...",
    
    // SearchFilters
    "search.placeholder": "搜索诊所、医生或专科...",
    "search.location": "位置",
    "search.filters": "筛选",
    "search.all": "全部",
    "search.gp": "全科",
    "search.tcm": "中医",
    "search.wellness": "健康",
    "search.specialists": "专科",
    
    // QuickGuide
    "guide.welcome": "欢迎来到ClynicQ！👋",
    "guide.description": "您的数字医疗保健伴侣。在新加坡各地排队、预约和连接医疗保健服务。",
    "guide.quickLinks": "快速链接：",
    "guide.joinQueue": "加入队列",
    "guide.appointments": "预约",
    "guide.healthAssistant": "健康助手",
    "guide.analytics": "分析",
    "guide.minimize": "最小化",
    "guide.gotIt": "知道了！",
    "guide.quickGuide": "快速指南",
    
    // OnboardingTour
    "tour.welcomeTitle": "欢迎来到ClynicQ！👋",
    "tour.welcomeDesc": "排队 • 预约 • 连接医疗保健服务。'Q'徽章显示所选诊所的活跃队列。",
    "tour.browseTitle": "浏览并加入队列 🏥",
    "tour.browseDesc": "查找诊所，检查实时队列，并从任何地方虚拟加入。",
    "tour.navTitle": "快速访问 🧭",
    "tour.navDesc": "使用菜单访问预约、健康助手和分析。",
    "tour.back": "返回",
    "tour.skip": "跳过",
    "tour.next": "下一步",
    "tour.gotIt": "知道了！",
    "tour.stepCount": "{current}/{total}",
    
    // MyClynicQPlugin
    "myclynicq.comingSoon": "即将推出",
    "myclynicq.title": "我的ClynicQ",
    "myclynicq.subtitle": "通过WhatsApp自动提醒和即时支持，不错过任何预约",
    "myclynicq.chatWhatsApp": "在WhatsApp上聊天",
    "myclynicq.alwaysAvailable": "您的健康助手，随时可用",
    "myclynicq.easyBooking": "轻松预约",
    "myclynicq.easyBookingDesc": "通过聊天预约、重新安排或取消预约",
    "myclynicq.smartReminders": "智能提醒",
    "myclynicq.smartRemindersDesc": "及时提醒，不会错过就诊",
    "myclynicq.instantAnswers": "即时回答",
    "myclynicq.instantAnswersDesc": "随时询问有关预约或诊所的问题",
    "myclynicq.queueUpdates": "队列更新",
    "myclynicq.queueUpdatesDesc": "无需致电诊所即可了解队列位置",
    "myclynicq.howItWorks": "工作原理",
    "myclynicq.step1": "在ClynicQ上预约",
    "myclynicq.step2": "在WhatsApp上收到确认消息",
    "myclynicq.step3": "在就诊前收到提醒",
    "myclynicq.step4": "随时与MyClynicQ聊天寻求帮助",
    "myclynicq.availableChannels": "可用渠道",
    "myclynicq.whatsapp": "WhatsApp",
    "myclynicq.sms": "短信",
    "myclynicq.webChat": "网页聊天",
    "myclynicq.stayConnected": "与您的医疗保健旅程保持联系。MyClynicQ让您随时了解情况，并使管理预约变得轻松。",
    
    // DoctorProfile
    "doctorProfile.loading": "正在加载医生资料...",
    "doctorProfile.notFound": "未找到医生",
    "doctorProfile.qualifications": "资质",
    "doctorProfile.languages": "语言",
    "doctorProfile.about": "关于",
    "doctorProfile.availability": "可预约时间",
    "doctorProfile.bookAppointment": "预约",
    "doctorProfile.viewClinic": "查看诊所",
    "doctorProfile.registration": "注册号",
    "doctorProfile.yearsExperience": "年经验",
    "doctorProfile.noQualifications": "无资质信息",
    "doctorProfile.noLanguages": "无语言信息",
    "doctorProfile.closed": "休息",
    
    // ClinicProfile
    "clinicProfile.bookAppointment": "预约挂号",
    "clinicProfile.joinQueue": "加入排队",
    "clinicProfile.clinicPhotos": "诊所照片",
    "clinicProfile.photoGalleryComingSoon": "照片库即将推出",
    "clinicProfile.phone": "电话",
    "clinicProfile.email": "电邮",
    "clinicProfile.notAvailable": "暂无",
    "clinicProfile.currentQueue": "当前排队",
    "clinicProfile.waiting": "等待中",
    "clinicProfile.doctors": "医生",
    "clinicProfile.awards": "奖项",
    "clinicProfile.operatingHours": "营业时间",
    "clinicProfile.reviews": "评价",
    "clinicProfile.verified": "已认证",
    "clinicProfile.yearsExperience": "年经验",
    "clinicProfile.qualifications": "资历与证书",
    "clinicProfile.noDoctorsAvailable": "暂无医生信息",
    "clinicProfile.awardsRecognition": "奖项与荣誉",
    "clinicProfile.awardedIn": "获奖年份",
    "clinicProfile.awardsComingSoon": "奖项和荣誉将在此显示",
    "clinicProfile.noReviews": "暂无评价",
    "clinicProfile.anonymous": "匿名用户",
    "clinicProfile.loading": "加载中...",
    "clinicProfile.signInToBook": "请登录以预约",
    "clinicProfile.failedToLoad": "无法加载诊所信息",
    
    // Consultant Section
    "consultant.badge": "专业指导",
    "consultant.pageTitle": "健康顾问",
    "consultant.pageDescription": "不确定选择哪家诊所？我们值得信赖的健康顾问将为您推荐合适的医疗服务提供者。",
    "consultant.searchPlaceholder": "按姓名或专业搜索...",
    "consultant.feature1Title": "个性化指导",
    "consultant.feature1Desc": "为您匹配合适的医疗服务",
    "consultant.feature2Title": "值得信赖的专家",
    "consultant.feature2Desc": "经过认证的医疗保健专业人员",
    "consultant.feature3Title": "免费咨询",
    "consultant.feature3Desc": "无任何义务或压力",
    "consultant.noResults": "未找到顾问",
    "consultant.noResultsDesc": "请尝试调整您的搜索条件",
    "consultant.viewProfile": "查看资料",
    "consultant.notFound": "未找到顾问",
    "consultant.backToList": "返回顾问列表",
    "consultant.getGuidance": "获取指导",
    "consultant.about": "关于",
    "consultant.services": "提供的服务",
    "consultant.patientTypes": "服务的患者类型",
    "consultant.needHelp": "需要帮助决定？",
    "consultant.needHelpDesc": "直接与此顾问交流，获取个性化建议。",
    "consultant.speakToConsultant": "联系顾问",
    "consultant.recommendedClinics": "推荐诊所",
    "consultant.recommendedBy": "由 {name} 推荐",
    
    // Admin Consultants
    "admin.consultantsTitle": "管理顾问",
    "admin.consultantsDesc": "添加、编辑和管理健康顾问",
    "admin.addConsultant": "添加顾问",
    "admin.editConsultant": "编辑顾问",
    "admin.name": "姓名",
    "admin.namePlaceholder": "输入顾问姓名",
    "admin.title": "职称",
    "admin.titlePlaceholder": "例如：健康顾问",
    "admin.photoUrl": "照片链接",
    "admin.shortBio": "简介",
    "admin.shortBioPlaceholder": "简短描述（2-3行）",
    "admin.fullBio": "详细介绍",
    "admin.fullBioPlaceholder": "详细的背景和经验",
    "admin.areasOfFocus": "专注领域",
    "admin.addAreaPlaceholder": "例如：疼痛管理",
    "admin.servicesOffered": "提供的服务",
    "admin.addServicePlaceholder": "例如：健康评估",
    "admin.patientTypes": "患者类型",
    "admin.addPatientTypePlaceholder": "例如：慢性疼痛患者",
    "admin.active": "活跃",
    "admin.inactive": "未激活",
    "admin.update": "更新",
    "admin.create": "创建",
    "admin.recommendedClinics": "推荐诊所",
    "admin.addClinic": "添加诊所",
    "admin.noConsultants": "暂无顾问",
    "admin.noConsultantsDesc": "添加您的第一位健康顾问以开始",
    "admin.nameRequired": "姓名为必填项",
    "admin.updateError": "更新顾问失败",
    "admin.createError": "创建顾问失败",
    "admin.consultantUpdated": "顾问更新成功",
    "admin.consultantCreated": "顾问创建成功",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "zh" ? "zh" : "en") as Language;
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
