// Language context with translations
import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.findClinics": "Find Clinics",
    "nav.staffDashboard": "Staff Dashboard",
    "nav.myAppointments": "My Appointments",
    "nav.healthAssistant": "Health Assistant",
    "nav.analytics": "Analytics",
    "nav.signOut": "Sign Out",
    "nav.login": "Login",
    "nav.signUp": "Sign Up",
    "nav.menu": "Menu",
    "nav.help": "Help & Support",
    "nav.restartTour": "Restart Tour",
    "nav.consultants": "Consultants",
    
    // Continuity & Support Services
    "continuity.badge": "Continuity & Support",
    "continuity.title": "Continuity & Support Services",
    "continuity.subtitle": "Beyond the clinic — services that support every stage of your healthcare journey.",
    "continuity.speakers.title": "Healthcare Speakers & Trainers",
    "continuity.speakers.desc": "Connect with experienced healthcare educators and trainers for workshops, talks, and professional development.",
    "continuity.afterlife.title": "After Life Services",
    "continuity.afterlife.desc": "Compassionate support and guidance for end-of-life planning, bereavement, and memorial services.",
    "continuity.endOfService.title": "Corporate & Community Health",
    "continuity.endOfService.desc": "Workplace health programmes, screenings and coordinated wellness initiatives.",
    "continuity.comingSoon": "Coming Soon",

    // Featured Consultants
    "featuredConsultants.badge": "Managed Healthcare",
    "featuredConsultants.title": "Not sure where to start?",
    "featuredConsultants.subtitle": "Get guided to the right care with our Managed Healthcare Providers.",
    "featuredConsultants.viewAll": "View All Providers",
    
    // Hero
    "hero.badge": "Check Queue • Book • Connect",
    "hero.title1": "Know Before",
    "hero.title2": "You Go",
    "hero.subtitle": "See queues, availability, and nearby care options before you decide where to go.",
    "hero.trustLine": "",
    "hero.findClinics": "Check Clinics Near Me",
    "hero.findMyQueue": "View My Queue Status",
    "hero.learnMore": "Learn More",
    "hero.queueTitle": "Queue Visibility",
    "hero.queueDesc": "Check estimated queue status before arrival",
    "hero.bookTitle": "Book",
    "hero.bookDesc": "Instant appointments across all clinics",
    "hero.connectTitle": "Connect",
    "hero.connectDesc": "AI health assistant & support",
    "hero.activityTitle": "🟢 Live queue activity",
    "hero.activityDesc": "Multiple clinics updating now",
    
    // Features
    "features.badge": "Features",
    "features.title": "What patients can do on ClynicQ",
    "features.subtitle": "",
    "features.queue.title": "Queue Visibility",
    "features.queue.subtitle": "",
    "features.queue.description": "See how many patients are ahead before joining.",
    "features.book.title": "Book or Contact",
    "features.book.subtitle": "",
    "features.book.description": "Use the clinic's available booking or contact flow without extra app installs.",
    "features.connect.title": "Guided Care Support",
    "features.connect.subtitle": "",
    "features.connect.description": "If you are unsure where to start, request guided routing to the right provider.",
    "features.secondary1.title": "Practitioner Profiles",
    "features.secondary2.title": "Nearby Options",
    "features.secondary3.title": "Multi-clinic Discovery",
    
    // Queue Page
    "queue.title": "Queue Status",
    "queue.loading": "Loading queue information...",
    "queue.inQueue": "In Queue",
    "queue.estWait": "Est. Wait",
    "queue.enableNotifications": "Get notified when it's nearly your turn",
    "queue.notificationDesc": "We'll send you an alert so you can time your arrival",
    "queue.complete": "Consultation Complete!",
    "queue.thankYou": "Thank you for visiting",
    "queue.rateVisit": "Rate your visit",
    "queue.feedbackThanks": "Thanks for your feedback!",
    "queue.feedbackHelps": "Your feedback helps us improve our service",
    "queue.returnHome": "Return to Home",
    "queue.bookAgain": "Book Again",
    "queue.beingServedNow": "You're Being Served Now!",
    "queue.proceedToConsultation": "Please proceed to the consultation area",
    "queue.yourQueueNumber": "Your Queue Number",
    "queue.checkedIn": "You're in the Queue!",
    "queue.updated": "Updated",
    "queue.ago": "ago",
    "queue.queueNumber": "Queue Number",
    "queue.status": "Status",
    "queue.waiting": "Waiting",
    "queue.estWaitTime": "Est. Wait",
    "queue.visitType": "Visit Type",
    "queue.peopleAhead": "People Ahead",
    "queue.generalConsultation": "General Consultation",
    "queue.notifiedWhenTurn": "We'll notify you when it's nearly your turn",
    "queue.leaveQueue": "Leave Queue",
    "queue.checkIn": "Check In",
    "queue.joinQueue": "Join Queue",
    "queue.notificationsOn": "Notifications On",
    "queue.enableAlerts": "Enable Alerts",
    "queue.minutes": "min",
    "queue.disclaimer.title": "Good to Know Before Joining",
    "queue.disclaimer.bullet1": "Queue order is managed by clinic staff and may change.",
    "queue.disclaimer.bullet2": "Number of patients ahead is a live operational guide, not a guaranteed wait time.",
    "queue.disclaimer.bullet3": "Urgent cases, walk-ins, or clinic prioritization may affect queue movement.",
    "queue.disclaimer.bullet4": "If you miss your turn, clinic handling will follow clinic policy.",
    "queue.disclaimer.understand": "I understand",
    "queue.queueShiftNotice": "Queue updated by clinic. Your estimated position has been adjusted.",
    "queue.preConsult.title": "Pre-Consultation Information",
    "queue.preConsult.visitReason": "Reason for Visit",
    "queue.preConsult.visitReasonPlaceholder": "Please describe your symptoms or reason for visit...",
    "queue.preConsult.visitType": "Visit Type",
    "queue.preConsult.continue": "Continue",
    "queue.smsConfirmation": "Save your queue link to check back anytime",
    
    // Staff Dashboard
    "staff.title": "Staff Dashboard",
    "staff.loading": "Loading staff dashboard...",
    "staff.queueStatus": "Queue Status:",
    "staff.open": "Open",
    "staff.closed": "Closed",
    "staff.totalToday": "Total Today",
    "staff.waiting": "Waiting",
    "staff.served": "Served",
    "staff.avgWait": "Avg Wait",
    "staff.currentQueue": "Current Queue",
    "staff.managePatients": "Manage patients waiting in line",
    "staff.callNextPatient": "Call Next Patient",
    "staff.noPatients": "No patients in queue",
    "staff.queueEmpty": "Queue is empty right now",
    "staff.patient": "Patient",
    "staff.waitingTime": "Waiting:",
    "staff.minutes2": "minutes",
    "staff.callPatient": "Call Patient",
    "staff.markServed": "Mark Served",
    "staff.cancel": "Cancel",
    "staff.noShow": "No-Show",
    "staff.moveUp": "Move up",
    "staff.moveDown": "Move down",
    "staff.addWalkIn": "Add Walk-In Patient",
    "staff.walkInName": "Patient Name",
    "staff.walkInPhone": "Phone Number",
    "staff.walkInNamePlaceholder": "Enter patient name",
    "staff.walkInPhonePlaceholder": "+65 XXXX XXXX",
    "staff.walkInAdded": "Walk-in patient added to queue",
    
    // Footer
    "footer.tagline": "Helping you plan clinic visits with less waiting",
    "footer.forPatients": "For Patients",
    "footer.findClinics": "Find Clinics",
    "footer.howItWorks": "How it Works",
    "footer.faq": "FAQ",
    "footer.forClinics": "For Clinics",
    "footer.joinPlatform": "Join Platform",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.company": "Company",
    "footer.aboutUs": "About Us",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.copyright": "© 2024 ClynicQ. PDPA Compliant Healthcare Platform.",
    
    // Appointments Page
    "appointments.title": "My Appointments",
    "appointments.bookNew": "Book New Appointment",
    "appointments.reason": "Reason",
    "appointments.noAppointments": "No appointments yet",
    "appointments.browseClinics": "Browse Clinics",
    "appointments.loading": "Loading...",
    "appointments.failedToLoad": "Failed to load appointments",
    "appointments.signInRequired": "Please sign in to view appointments",
    
    // Analytics Page
    "analytics.title": "Analytics Dashboard",
    "analytics.phase4": "Phase 4 - Data Insights",
    "analytics.overview": "Last 30 days overview",
    "analytics.operationalTrends": "Operational Trends",
    "analytics.totalPatients": "Total Patients",
    "analytics.queueEntries": "Queue entries",
    "analytics.avgWaitTime": "Avg Wait Time",
    "analytics.perPatient": "Per patient",
    "analytics.appointments": "Appointments",
    "analytics.booked": "Booked",
    "analytics.noShowRate": "No-Show Rate",
    "analytics.noShows": "no-shows",
    "analytics.behaviorSignals": "Patient Behavior Signals",
    "analytics.bookingPatterns": "Booking Patterns",
    "analytics.bookingQuestion": "How far in advance do patients book?",
    "analytics.avgBookingWindow": "Average Booking Window",
    "analytics.days": "days",
    "analytics.returnPatientRate": "Return Patient Rate",
    "analytics.peakActivity": "Peak Activity",
    "analytics.commonPatterns": "Most common booking patterns",
    "analytics.patients": "patients",
    "analytics.performanceBenchmark": "Performance Benchmarking",
    "analytics.comparePerformance": "Compare your clinic's performance over time",
    "analytics.queueEfficiency": "Queue Efficiency",
    "analytics.waitTimeVsStandard": "Average wait time vs industry standard",
    "analytics.excellent": "Excellent",
    "analytics.needsImprovement": "Needs Improvement",
    "analytics.patientRetention": "Patient Retention",
    "analytics.returnRateVsAverage": "Return patient rate vs industry average",
    "analytics.aboveAverage": "Above Average",
    "analytics.average": "Average",
    "analytics.attendanceRate": "Attendance Rate",
    "analytics.noShowVsBenchmark": "No-show rate vs industry benchmark",
    "analytics.needsAttention": "Needs Attention",
    "analytics.loadingAnalytics": "Loading analytics...",
    "analytics.accessDenied": "Access denied. Only clinic staff can view analytics.",
    
    // Booking Page
    "booking.title": "Book Appointment",
    "booking.selectDoctor": "Select Doctor (Optional)",
    "booking.anyDoctor": "Any available doctor",
    "booking.selectDate": "Select Date",
    "booking.selectTime": "Select Time",
    "booking.reasonForVisit": "Reason for Visit",
    "booking.reasonPlaceholder": "Brief description of your symptoms or reason for visit...",
    "booking.cancel": "Cancel",
    "booking.confirmBooking": "Confirm Booking",
    "booking.booking": "Booking...",
    "booking.signInRequired": "Please sign in to book an appointment",
    "booking.selectDateTime": "Please select both date and time",
    "booking.bookingSuccess": "Appointment booked successfully!",
    "booking.failedToLoad": "Failed to load clinic information",
    "booking.bookingFailed": "Failed to book appointment",
    "booking.loading": "Loading...",
    
    // Chatbot Page
    "chatbot.title": "Health Assistant",
    "chatbot.subtitle": "Ask me anything about your health",
    "chatbot.placeholder": "Type your message...",
    "chatbot.disclaimer": "This is an AI assistant. Always consult with healthcare professionals for medical advice.",
    "chatbot.welcome": "Hello! I'm your ClynicQ health assistant. I can help you with:\n\n• Symptom assessment\n• Health advice\n• Appointment preparation\n• Post-consultation care\n\nHow can I assist you today?",
    "chatbot.errorMessage": "I'm sorry, I encountered an error. Please try again.",
    "chatbot.failedToSend": "Failed to send message",
    
    // Dashboard Page
    "dashboard.title": "Clinic Dashboard",
    "dashboard.todayAppointments": "Today's Appointments",
    "dashboard.inQueue": "In Queue",
    "dashboard.pendingApproval": "Pending Approval",
    "dashboard.totalUpcoming": "Total Upcoming",
    "dashboard.appointments": "Appointments",
    "dashboard.queue": "Queue",
    "dashboard.plugins": "Plugins",
    "dashboard.confirm": "Confirm",
    "dashboard.decline": "Decline",
    "dashboard.noUpcoming": "No upcoming appointments",
    "dashboard.noOneInQueue": "No one in queue",
    "dashboard.loading": "Loading...",
    "dashboard.accessDenied": "You don't have access to the dashboard",
    "dashboard.noClinic": "No clinic assigned to your account",
    "dashboard.failedToLoad": "Failed to load dashboard data",
    "dashboard.confirmed": "confirmed",
    "dashboard.cancelled": "cancelled",
    "dashboard.estWait": "Est. wait",
    "dashboard.walkIn": "Walk-in Patient",
    
    // Auth Page
    "auth.welcomeBack": "Welcome Back",
    "auth.enterCredentials": "Enter your credentials to access your account",
    "auth.createAccount": "Create Account",
    "auth.signupDescription": "Sign up to start booking appointments",
    "auth.email": "Email",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "Password",
    "auth.fullName": "Full Name",
    "auth.namePlaceholder": "John Doe",
    "auth.confirmPassword": "Confirm Password",
    "auth.signIn": "Sign In",
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.termsAgreement": "By continuing, you agree to our Terms of Service and Privacy Policy",
    "auth.invalidEmail": "Invalid email address",
    "auth.passwordLength": "Password must be at least 6 characters",
    "auth.passwordMismatch": "Passwords don't match",
    "auth.nameTooShort": "Name must be at least 2 characters",
    
    // NotFound Page
    "notFound.title": "404",
    "notFound.message": "Oops! Page not found",
    "notFound.returnHome": "Return to Home",
    
    // ClinicCard
    "clinicCard.open": "Open",
    "clinicCard.closed": "Closed",
    "clinicCard.inQueue": "In Queue",
    "clinicCard.people": "people",
    "clinicCard.estWait": "Est. Wait",
    "clinicCard.youreInQueue": "You're in the Queue",
    "clinicCard.position": "Position",
    "clinicCard.of": "of",
    "clinicCard.waiting": "Waiting",
    "clinicCard.checkIn": "Check In",
    "clinicCard.leaveQueue": "Leave Queue",
    "clinicCard.readyToSkip": "Check Queue",
    "clinicCard.joinVirtual": "See how many people are ahead",
    "clinicCard.visitType": "Visit Type",
    "clinicCard.generalConsultation": "General Consultation",
    "clinicCard.followUp": "Follow-up",
    "clinicCard.emergency": "Emergency",
    "clinicCard.vaccination": "Vaccination",
    "clinicCard.healthScreening": "Health Screening",
    "clinicCard.joinQueue": "Join Queue",
    "clinicCard.joining": "Joining...",
    "clinicCard.viewDetails": "View Details",
    "clinicCard.queueSuccess": "You're #{number} in the queue! Save your link to check back anytime.",
    "clinicCard.alreadyInQueue": "You're already in this queue!",
    "clinicCard.leftQueue": "Left the queue successfully",
    "clinicCard.failedToLeave": "Failed to leave queue",
    "clinicCard.checkedIn": "Checked in successfully!",
    "clinicCard.signInRequired": "Please sign in to join the queue",
    "clinicCard.failedToJoin": "Failed to join queue",
    "clinicCard.availabilitiesToday": "Availabilities Today",
    "clinicCard.servicesOffered": "Services Offered",
    "clinicCard.joinedQueue": "You've joined the queue! Save your link to revisit anytime.",
    
    // MarketplaceSection
    "marketplace.title": "Find Your Clinic",
    "marketplace.subtitle": "Browse clinics near you, check estimated queue status, and plan your visit with less waiting",
    "marketplace.loading": "Loading clinics...",
    
    // SearchFilters
    "search.placeholder": "Search clinics, doctors, or specialties...",
    "search.location": "Location",
    "search.filters": "Filters",
    "search.all": "All",
    "search.gp": "GP",
    "search.tcm": "TCM",
    "search.wellness": "Wellness",
    "search.specialists": "Specialists",
    
    // QuickGuide
    "guide.welcome": "Welcome to ClynicQ! 👋",
    "guide.description": "Your pre-arrival healthcare companion. Check queue estimates, book appointments, and connect with healthcare services across Singapore.",
    "guide.quickLinks": "Quick Links:",
    "guide.joinQueue": "Check Queue",
    "guide.appointments": "Appointments",
    "guide.healthAssistant": "Health Assistant",
    "guide.analytics": "Analytics",
    "guide.minimize": "Minimize",
    "guide.gotIt": "Got it!",
    "guide.quickGuide": "Quick Guide",
    
    // OnboardingTour
    "tour.welcomeTitle": "Welcome to ClynicQ! 👋",
    "tour.welcomeDesc": "Check Queue • Book • Connect with healthcare services. The 'Q' badge shows estimated queue activity at participating clinics.",
    "tour.browseTitle": "Browse & Check Queues 🏥",
    "tour.browseDesc": "Find clinics, check estimated queue status, and plan your visit before heading out.",
    "tour.navTitle": "Quick Access 🧭",
    "tour.navDesc": "Use the menu to access appointments, health assistant, and analytics.",
    "tour.back": "Back",
    "tour.skip": "Skip",
    "tour.next": "Next",
    "tour.gotIt": "Got it!",
    "tour.stepCount": "{current} of {total}",
    
    // MyClynicQPlugin
    "myclynicq.comingSoon": "Coming Soon",
    "myclynicq.title": "MyClynicQ",
    "myclynicq.subtitle": "Never miss an appointment with automated reminders and instant support on WhatsApp",
    "myclynicq.chatWhatsApp": "Chat on WhatsApp",
    "myclynicq.alwaysAvailable": "Your health assistant, always available",
    "myclynicq.easyBooking": "Easy Booking",
    "myclynicq.easyBookingDesc": "Book, reschedule, or cancel appointments via chat",
    "myclynicq.smartReminders": "Smart Reminders",
    "myclynicq.smartRemindersDesc": "Get timely reminders so you never miss a visit",
    "myclynicq.instantAnswers": "Instant Answers",
    "myclynicq.instantAnswersDesc": "Ask questions about your appointment or clinic anytime",
    "myclynicq.queueUpdates": "Queue Updates",
    "myclynicq.queueUpdatesDesc": "Know your queue position without calling the clinic",
    "myclynicq.howItWorks": "How It Works",
    "myclynicq.step1": "Book an appointment on ClynicQ",
    "myclynicq.step2": "Get a confirmation message on WhatsApp",
    "myclynicq.step3": "Receive reminders before your visit",
    "myclynicq.step4": "Chat with MyClynicQ anytime for help",
    "myclynicq.availableChannels": "Available Channels",
    "myclynicq.whatsapp": "WhatsApp",
    "myclynicq.sms": "SMS",
    "myclynicq.webChat": "Web Chat",
    "myclynicq.stayConnected": "Stay connected with your healthcare journey. MyClynicQ keeps you informed and makes managing appointments effortless.",
    
    // DoctorProfile
    "doctorProfile.loading": "Loading doctor profile...",
    "doctorProfile.notFound": "Doctor not found",
    "doctorProfile.qualifications": "Qualifications",
    "doctorProfile.languages": "Languages",
    "doctorProfile.about": "About",
    "doctorProfile.availability": "Availability",
    "doctorProfile.bookAppointment": "Book Appointment",
    "doctorProfile.viewClinic": "View Clinic",
    "doctorProfile.registration": "Reg",
    "doctorProfile.yearsExperience": "years experience",
    "doctorProfile.noQualifications": "No qualifications listed",
    "doctorProfile.noLanguages": "No languages listed",
    "doctorProfile.closed": "Closed",
    
    // ClinicProfile
    "clinicProfile.bookAppointment": "Book Appointment",
    "clinicProfile.joinQueue": "Join Queue",
    "clinicProfile.clinicPhotos": "Clinic Photos",
    "clinicProfile.photoGalleryComingSoon": "Photo gallery coming soon",
    "clinicProfile.phone": "Phone",
    "clinicProfile.email": "Email",
    "clinicProfile.notAvailable": "Not available",
    "clinicProfile.currentQueue": "Current Queue",
    "clinicProfile.waiting": "waiting",
    "clinicProfile.doctors": "Doctors",
    "clinicProfile.awards": "Awards",
    "clinicProfile.operatingHours": "Operating Hours",
    "clinicProfile.reviews": "Reviews",
    "clinicProfile.verified": "Verified",
    "clinicProfile.yearsExperience": "years experience",
    "clinicProfile.qualifications": "Qualifications & Certificates",
    "clinicProfile.noDoctorsAvailable": "No doctors information available",
    "clinicProfile.awardsRecognition": "Awards & Recognition",
    "clinicProfile.awardedIn": "Awarded in",
    "clinicProfile.awardsComingSoon": "Awards and recognition will be displayed here",
    "clinicProfile.noReviews": "No reviews yet",
    "clinicProfile.anonymous": "Anonymous",
    "clinicProfile.loading": "Loading...",
    "clinicProfile.signInToBook": "Please sign in to book an appointment",
    "clinicProfile.failedToLoad": "Failed to load clinic information",
    "clinicProfile.requestManagedCare": "Request Managed Care Support",
    "clinicProfile.managedCareSubtitle": "NMG will coordinate your appointment and contact you shortly.",
    "clinicProfile.fieldName": "Name",
    "clinicProfile.fieldPhone": "Phone Number",
    "clinicProfile.fieldTiming": "Preferred Timing",
    "clinicProfile.fieldConcern": "Brief Concern",
    "clinicProfile.fieldTimingPlaceholder": "e.g. Weekday mornings",
    "clinicProfile.fieldConcernPlaceholder": "Briefly describe your concern",
    "clinicProfile.submitRequest": "Submit Request",
    "clinicProfile.submitting": "Submitting...",
    "clinicProfile.requestReceived": "Request received. NMG will contact you shortly.",
    
    // Consultant Section
    "consultant.badge": "Expert Guidance",
    "consultant.pageTitle": "Managed Healthcare Providers",
    "consultant.pageDescription": "Not sure which clinic to choose? Our trusted managed healthcare providers guide you to the right healthcare services.",
    "consultant.searchPlaceholder": "Search by name or specialty...",
    "consultant.feature1Title": "Personalized Guidance",
    "consultant.feature1Desc": "Get matched to the right provider",
    "consultant.feature2Title": "Trusted Experts",
    "consultant.feature2Desc": "Verified healthcare professionals",
    "consultant.feature3Title": "Free Consultation",
    "consultant.feature3Desc": "No obligation, no pressure",
    "consultant.noResults": "No consultants found",
    "consultant.noResultsDesc": "Try adjusting your search criteria",
    "consultant.viewProfile": "View Profile",
    "consultant.notFound": "Consultant not found",
    "consultant.backToList": "Back to Consultants",
    "consultant.getGuidance": "Get Guidance",
    "consultant.about": "About",
    "consultant.services": "Services Offered",
    "consultant.patientTypes": "Types of Patients",
    "consultant.needHelp": "Need Help Deciding?",
    "consultant.needHelpDesc": "Speak directly with this advisor for personalized recommendations.",
    "consultant.speakToConsultant": "Speak to Consultant",
    "consultant.recommendedClinics": "Recommended Clinics",
    "consultant.recommendedBy": "Recommended by {name}",
    
    // Admin Consultants
    "admin.consultantsTitle": "Manage Consultants",
    "admin.consultantsDesc": "Add, edit, and manage healthcare providers",
    "admin.addConsultant": "Add Consultant",
    "admin.editConsultant": "Edit Consultant",
    "admin.name": "Name",
    "admin.namePlaceholder": "Enter consultant name",
    "admin.title": "Title",
    "admin.titlePlaceholder": "e.g. Wellness Advisor",
    "admin.photoUrl": "Photo URL",
    "admin.shortBio": "Short Bio",
    "admin.shortBioPlaceholder": "Brief description (2-3 lines)",
    "admin.fullBio": "Full Bio",
    "admin.fullBioPlaceholder": "Detailed background and experience",
    "admin.areasOfFocus": "Areas of Focus",
    "admin.addAreaPlaceholder": "e.g. Pain Management",
    "admin.servicesOffered": "Services Offered",
    "admin.addServicePlaceholder": "e.g. Health Assessment",
    "admin.patientTypes": "Patient Types",
    "admin.addPatientTypePlaceholder": "e.g. Chronic Pain Patients",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.update": "Update",
    "admin.create": "Create",
    "admin.recommendedClinics": "Recommended Clinics",
    "admin.addClinic": "Add Clinic",
    "admin.noConsultants": "No consultants yet",
    "admin.noConsultantsDesc": "Add your first healthcare provider to get started",
    "admin.nameRequired": "Name is required",
    "admin.updateError": "Failed to update consultant",
    "admin.createError": "Failed to create consultant",
    "admin.consultantUpdated": "Consultant updated successfully",
    "admin.consultantCreated": "Consultant created successfully",

    // Organization (NYMG)
    "org.name": "Nanyang Medical Group",
    "org.subtitle": "Managed Healthcare Provider",
    "org.tagline": "Integrated healthcare network delivering coordinated patient care across multiple disciplines.",
    "org.highlight1": "Multi-Clinic Network",
    "org.highlight2": "GP & Specialist Care",
    "org.highlight3": "Coordinated Care Pathways",
    "org.viewProvider": "View Provider",
    "org.heroIntro": "Nanyang Medical Group is a managed healthcare provider offering coordinated care across general practice, specialist services, and allied health.",
    "org.startConsultation": "Start Consultation",
    "org.viewServices": "View Services",
    "org.aboutTitle": "About Nanyang Medical Group",
    "org.aboutBody": "Nanyang Medical Group operates as an integrated healthcare ecosystem, supporting patients across multiple care touchpoints. Through coordinated workflows and structured provider networks, patients are guided seamlessly from intake to treatment and follow-up.",
    "org.howItWorksTitle": "How It Works",
    "org.stepLabel": "Step",
    "org.step1Title": "Submit Intake",
    "org.step1Desc": "Patient fills up a structured intake form.",
    "org.step2Title": "Matching & Coordination",
    "org.step2Desc": "Appropriate medical concierge or provider is assigned.",
    "org.step3Title": "Direct Follow-up",
    "org.step3Desc": "Conversation continues via WhatsApp for fast response.",
    "org.conciergeTitle": "Medical Concierge Team",
    "org.connect": "Connect",
    "org.noConcierges": "No concierge profiles available yet.",
    "org.servicesTitle": "Services Overview",
    "org.service.general": "General Consultation",
    "org.service.chronic": "Chronic Care",
    "org.service.specialist": "Specialist Referral",
    "org.service.preventive": "Preventive Health",
    "org.heroDesc": "Patient access across general practice, specialist care, and referral services — managed through a single network.",
    "org.oneEntry": "One Entry",
    "org.weMatchYou": "We Match You",
    "org.weFollowUp": "We Follow Up",
    "org.networkCapabilities": "Network Capabilities",
    "org.clinicNetwork": "Clinic Network",
    "org.specialistAccess": "Specialist Access",
    "org.coverageSupport": "Coverage Support",
    "org.whyConciergeTitle": "Why Medical Concierge Care Exists",
    "org.whyConciergeDesc": "Healthcare is not a single system — patients often navigate multiple providers, referrals, and steps on their own.",
    "org.whyConciergeSimplifies": "This model simplifies it:",
    "org.whyConcierge.oneIntake": "One intake",
    "org.whyConcierge.guidedMatching": "Guided provider matching",
    "org.whyConcierge.continuousFollowUp": "Continuous follow-up",
    "org.careComparison": "Care Experience Comparison",
    "org.unstructured": "Unstructured",
    "org.unstructured.multipleEntry": "Multiple entry points",
    "org.unstructured.noProvider": "No clear provider choice",
    "org.unstructured.manualCoord": "Manual coordination",
    "org.unstructured.fragmented": "Fragmented care",
    "org.nanyangModel": "Nanyang Model",
    "org.nanyang.singleEntry": "Single entry",
    "org.nanyang.guidedMatching": "Guided matching",
    "org.nanyang.structuredHandoff": "Structured handoff",
    "org.nanyang.continuousCare": "Continuous care",
    "org.intakeFlowTitle": "Patient Intake Flow",
    "org.intakeStep1": "Submit your condition or concern",
    "org.intakeStep2": "Get matched to the right provider",
    "org.intakeStep3": "Continue instantly via WhatsApp",
    "org.intakeNote": "No app download needed. You pay the clinic directly — no additional fees.",
    "org.exampleIntakePreview": "Example intake preview",
    "org.fakeField.condition": "Condition / Concern",
    "org.fakeField.conditionVal": "Chronic back pain management",
    "org.fakeField.location": "Preferred Location",
    "org.fakeField.locationVal": "Central / East",
    "org.fakeField.urgency": "Urgency",
    "org.fakeField.urgencyVal": "Soon",
    "org.fakeField.contact": "Contact",
    "org.availableCareAreas": "Available Care Areas",
    "org.carePathways": "Care Pathways",
    "org.careCoordTeam": "Care Coordination Team",
    "org.careCoordDesc": "Each coordinator guides you from intake to the right care provider.",
    "org.active": "Active",
    "org.start": "Start",
    "org.noConciergesAvailable": "No concierges available at this time.",
    "org.multiClinic": "Multi-Clinic",
    "org.patientFlow": "Patient Flow",
    "org.careDelivery": "Care Delivery",
    "org.howCareCoordWorks": "How Care Coordination Works",
    "org.howStep1": "Submit Intake",
    "org.howStep1Desc": "Structured care request form",
    "org.howStep2": "Case Matching",
    "org.howStep2Desc": "Assigned to the right provider",
    "org.howStep3": "Follow-up via WhatsApp",
    "org.howStep3Desc": "Immediate patient response",

    // SHA
    "sha.badge": "Panel of Specialists",
    "sha.name": "Singapore HealthCare Alliance",
    "sha.heroDesc": "Access a wide panel of specialist doctors across multiple disciplines in Singapore.",
    "sha.multipleHospitals": "Multiple Hospitals",
    "sha.whatsappContact": "WhatsApp Contact",
    "sha.hospitalLocations": "Hospital Locations",
    "sha.specialistDisciplines": "Specialist Disciplines",
    "sha.specialistDesc": "Specialist disciplines available include surgical, medical and sub-specialty care across multiple fields.",
    "sha.keyProcedures": "Key Procedures & Services",
    "sha.procedure1": "Colonoscopy and gastroscopy",
    "sha.procedure2": "Gastric sleeve surgery",
    "sha.procedure3": "Hernia repair",
    "sha.procedure4": "Prostate surgery",
    "sha.procedure5": "Breast biopsy and breast cancer surgery",
    "sha.procedure6": "Tonsil and adenoid surgery",
    "sha.findSpecialist": "Find Your Specialist",
    "sha.findSpecialistDesc": "Contact us via WhatsApp or hotline to connect with a specialist.",
    "sha.journeyStep1": "Describe your condition",
    "sha.journeyStep2": "Contact via WhatsApp",
    "sha.journeyStep3": "Receive specialist guidance",
    "sha.startWithDr": "Start with Dr Richard Kwok →",
    "sha.noAppNeeded": "No app download needed. Contact is made directly via WhatsApp.",
    "sha.intakeDesc": "Describe your condition and we will connect you to the appropriate specialist.",
    "sha.exampleIntakePreview": "Example intake preview",
    "sha.fakeField.condition": "Condition / Concern",
    "sha.fakeField.conditionVal": "Recurring knee discomfort",
    "sha.fakeField.location": "Preferred Location",
    "sha.fakeField.locationVal": "West / Jurong",
    "sha.fakeField.urgency": "Urgency",
    "sha.fakeField.urgencyVal": "Within a week",
    "sha.fakeField.contact": "Contact",
    "sha.careCoordination": "Care Coordination",
    "sha.careCoordDesc": "Care coordination led by Dr Richard Kwok.",
    "sha.noCoordinators": "No coordinators available at this time.",
    "sha.availableCareAreas": "Available Care Areas",
    "sha.carePathways": "Care Pathways",
    "sha.generalPractice": "General Practice",
    "sha.chronicDisease": "Chronic Disease",
    "sha.specialistReferral": "Specialist Referral",
    "sha.rehabilitation": "Rehabilitation",
    "sha.mentalWellness": "Mental Wellness",
    "sha.active": "Active",
    "sha.start": "Start",

    // Speakers & Trainers
    "speakers.badge": "Healthcare Speakers & Trainers",
    "speakers.title": "Healthcare Speakers & Trainers",
    "speakers.desc": "Connect with experienced healthcare speakers and trainers for corporate wellness, community health, and professional development.",
    "speakers.expertSpeakers": "Expert Speakers",
    "speakers.expertSpeakersDesc": "Industry-experienced professionals",
    "speakers.customProgrammes": "Custom Programmes",
    "speakers.customProgrammesDesc": "Tailored to your organisation",
    "speakers.corporateCommunity": "Corporate & Community",
    "speakers.corporateCommunityDesc": "For workplaces and communities",

    // Speaker Profile (Ouch)
    "speakerProfile.badge": "Healthcare Speaker & Trainer",
    "speakerProfile.heroDesc": "Corporate health talks, TCM wellness workshops, and healthcare training — led by Hui Fang.",
    "speakerProfile.enquire": "Enquire",
    "speakerProfile.weCustomise": "We Customise",
    "speakerProfile.weDeliver": "We Deliver",
    "speakerProfile.capabilities": "Capabilities",
    "speakerProfile.tcmHealthTalks": "TCM Health Talks",
    "speakerProfile.b2bWorkshops": "B2B & B2C Workshops",
    "speakerProfile.corporateTraining": "Corporate Training",
    "speakerProfile.aboutUs": "About Us",
    "speakerProfile.aboutDesc": "Ouch Pte Ltd specialises in Traditional Chinese Medicine (TCM) education and wellness training for corporate (B2B) and consumer (B2C) audiences. From corporate wellness days to community health events, Ouch delivers engaging workshops and health talks that bridge traditional wisdom with modern wellness — covering stress management, acupressure self-care, dietary therapy, and holistic health.",
    "speakerProfile.leadSpeaker": "Lead Speaker & TCM Educator",
    "speakerProfile.huiFangBio": "Hui Fang is a certified TCM practitioner and healthcare educator with years of experience delivering corporate wellness talks and community workshops. She specialises in making TCM concepts practical and relatable for modern audiences.",
    "speakerProfile.tcmWorkshopsTag": "TCM Workshops",
    "speakerProfile.corporateWellnessTag": "Corporate Wellness",
    "speakerProfile.healthEducationTag": "Health Education",
    "speakerProfile.connectWithHuiFang": "Connect with Hui Fang",
    "speakerProfile.howItWorks": "How It Works",
    "speakerProfile.step1": "Submit your enquiry or event details",
    "speakerProfile.step2": "Get a customised programme proposal",
    "speakerProfile.step3": "Confirm and we deliver on-site",
    "speakerProfile.flexibility": "Flexible scheduling. Tailored content for your audience — from corporate teams to community groups.",
    "speakerProfile.exampleEnquiry": "Example enquiry",
    "speakerProfile.fakeField.eventType": "Event Type",
    "speakerProfile.fakeField.eventTypeVal": "Corporate TCM Wellness Workshop",
    "speakerProfile.fakeField.audience": "Audience",
    "speakerProfile.fakeField.audienceVal": "50 employees, finance team",
    "speakerProfile.fakeField.format": "Format",
    "speakerProfile.fakeField.formatVal": "B2B — onsite, 90 min",
    "speakerProfile.fakeField.contact": "Contact",
    "speakerProfile.whyOuch": "Why Ouch Pte Ltd",
    "speakerProfile.whyOuchDesc": "Healthcare education needs to be engaging, evidence-based, and relevant to your audience.",
    "speakerProfile.whatSetsUsApart": "What sets us apart:",
    "speakerProfile.apart1": "TCM-focused expertise",
    "speakerProfile.apart2": "B2B & B2C programmes",
    "speakerProfile.apart3": "Customised to your industry",
    "speakerProfile.apart4": "Interactive & engaging delivery",
    "speakerProfile.experienceComparison": "Experience Comparison",
    "speakerProfile.genericTalks": "Generic Talks",
    "speakerProfile.generic1": "One-size-fits-all",
    "speakerProfile.generic2": "No clinical backing",
    "speakerProfile.generic3": "Passive delivery",
    "speakerProfile.generic4": "Low engagement",
    "speakerProfile.ouchModel": "Ouch Model",
    "speakerProfile.ouch1": "TCM-customised",
    "speakerProfile.ouch2": "Evidence-based",
    "speakerProfile.ouch3": "Interactive workshops",
    "speakerProfile.ouch4": "Measurable outcomes",
    "speakerProfile.availableProgrammes": "Available Programmes",
    "speakerProfile.serviceAreas": "Service Areas",
    "speakerProfile.b2bCorporateWorkshops": "B2B Corporate Workshops",
    "speakerProfile.b2cCommunitySessions": "B2C Community Sessions",
    "speakerProfile.professionalTraining": "Professional Training",
    "speakerProfile.readyToBook": "Ready to book a session?",
    "speakerProfile.readyToBookDesc": "Submit your enquiry and we'll get back to you with a customised proposal.",
    "speakerProfile.enquireNow": "Enquire Now",

    // Afterlife Services page
    "afterlife.badge": "After Life Services",
    "afterlife.title": "After Life Services",
    "afterlife.desc": "Compassionate end-of-life planning, memorial services, and bereavement support for families.",
    "afterlife.compassionateCare": "Compassionate Care",
    "afterlife.compassionateCareDesc": "Dignified & respectful services",
    "afterlife.prePlanning": "Pre-Planning",
    "afterlife.prePlanningDesc": "Advance arrangements available",
    "afterlife.familySupport": "Family Support",
    "afterlife.familySupportDesc": "Bereavement & grief counselling",

    // Afterlife Profile (Nirvana)
    "afterlifeProfile.heroDesc": "Comprehensive memorial planning, bereavement support, and dignified afterlife services for families.",
    "afterlifeProfile.reachOut": "Reach Out",
    "afterlifeProfile.weGuideYou": "We Guide You",
    "afterlifeProfile.weSupport": "We Support",
    "afterlifeProfile.enquireNow": "Enquire Now",
    "afterlifeProfile.services": "Services",
    "afterlifeProfile.memorialServices": "Memorial Services",
    "afterlifeProfile.prePlanning": "Pre-Planning",
    "afterlifeProfile.bereavementSupport": "Bereavement Support",
    "afterlifeProfile.aboutTitle": "About Nirvana",
    "afterlifeProfile.aboutP1": "Nirvana is a trusted provider of comprehensive afterlife and memorial services. With a deep commitment to compassion and dignity, Nirvana helps families navigate end-of-life planning, memorial arrangements, and bereavement support — ensuring every family receives the care and guidance they deserve during difficult times.",
    "afterlifeProfile.aboutP2": "From pre-need planning to immediate arrangements, Nirvana's experienced team of consultants provides personalised guidance across all cultural and religious traditions, making the process as gentle and seamless as possible.",
    "afterlifeProfile.ourConsultants": "Our Consultants",
    "afterlifeProfile.connectWithAdvisor": "Connect with a Nirvana Advisor",
    "afterlifeProfile.connectDesc": "Speak to an experienced advisor who can guide you with care.",
    "afterlifeProfile.connect": "Connect",
    "afterlifeProfile.howItWorks": "How It Works",
    "afterlifeProfile.howStep1": "Reach out with your needs or enquiry",
    "afterlifeProfile.howStep2": "Get guided through available options",
    "afterlifeProfile.howStep3": "Continuous support throughout the process",
    "afterlifeProfile.howNote": "Compassionate guidance every step of the way. No pressure — just support when you need it.",
    "afterlifeProfile.startEnquiry": "Start Your Enquiry",
    "afterlifeProfile.exampleEnquiry": "Example enquiry",
    "afterlifeProfile.fakeField.serviceType": "Service Type",
    "afterlifeProfile.fakeField.serviceTypeVal": "Memorial Planning",
    "afterlifeProfile.fakeField.arrangement": "Preferred Arrangement",
    "afterlifeProfile.fakeField.arrangementVal": "Traditional / Modern",
    "afterlifeProfile.fakeField.timeline": "Timeline",
    "afterlifeProfile.fakeField.timelineVal": "Flexible",
    "afterlifeProfile.fakeField.contact": "Contact",
    "afterlifeProfile.whyNirvana": "Why Nirvana",
    "afterlifeProfile.whyNirvanaDesc": "End-of-life planning deserves dignity, compassion, and professional guidance.",
    "afterlifeProfile.whatSetsUsApart": "What sets us apart:",
    "afterlifeProfile.apart1": "Established & trusted provider",
    "afterlifeProfile.apart2": "Comprehensive service range",
    "afterlifeProfile.apart3": "Family-centred approach",
    "afterlifeProfile.apart4": "Multi-cultural sensitivity",
    "afterlifeProfile.serviceComparison": "Service Comparison",
    "afterlifeProfile.withoutGuidance": "Without Guidance",
    "afterlifeProfile.without1": "Overwhelming options",
    "afterlifeProfile.without2": "No clear process",
    "afterlifeProfile.without3": "Emotional burden",
    "afterlifeProfile.without4": "Last-minute decisions",
    "afterlifeProfile.nirvanaModel": "Nirvana Model",
    "afterlifeProfile.nirvana1": "Guided planning",
    "afterlifeProfile.nirvana2": "Clear process",
    "afterlifeProfile.nirvana3": "Emotional support",
    "afterlifeProfile.nirvana4": "Advance arrangements",
    "afterlifeProfile.needGuidance": "Need guidance or support?",
    "afterlifeProfile.needGuidanceDesc": "Reach out to our team for a compassionate, no-obligation conversation.",

    // Afterlife Profile Agent data
    "afterlifeProfile.agent1.name": "Sarah Lim",
    "afterlifeProfile.agent1.title": "Senior Afterlife Consultant",
    "afterlifeProfile.agent1.bio": "Over 10 years of experience guiding families through memorial planning with compassion and professionalism.",
    "afterlifeProfile.agent1.tag1": "Memorial Planning",
    "afterlifeProfile.agent1.tag2": "Pre-Need Arrangements",
    "afterlifeProfile.agent1.tag3": "Family Support",
    "afterlifeProfile.agent2.name": "David Tan",
    "afterlifeProfile.agent2.title": "Bereavement Support Advisor",
    "afterlifeProfile.agent2.bio": "Specialises in bereavement counselling and helping families navigate end-of-life decisions with care and sensitivity.",
    "afterlifeProfile.agent2.tag1": "Grief Counselling",
    "afterlifeProfile.agent2.tag2": "Cultural Services",
    "afterlifeProfile.agent2.tag3": "Estate Guidance",
    "afterlifeProfile.agent3.name": "Michelle Wong",
    "afterlifeProfile.agent3.title": "Pre-Planning Specialist",
    "afterlifeProfile.agent3.bio": "Helps individuals and families with advance planning, ensuring wishes are documented and arrangements are prepared.",
    "afterlifeProfile.agent3.tag1": "Advance Planning",
    "afterlifeProfile.agent3.tag2": "Documentation",
    "afterlifeProfile.agent3.tag3": "Financial Planning",

    // For Clinics page
    "forClinics.thankYou": "Thank you!",
    "forClinics.thankYouDesc": "Thanks, we've received your request. We'll reach out shortly.",
    "forClinics.title": "Improve patient flow without changing your current system",
    "forClinics.subtitle": "ClynicQ helps clinics reduce front desk interruptions, manage walk-ins, and give patients visibility before they arrive.",
    "forClinics.bullet1": "Reduce repeated queue questions and front desk interruptions",
    "forClinics.bullet2": "Let patients check queue load before arriving",
    "forClinics.bullet3": "Maintain your existing booking and clinic workflow",
    "forClinics.clinicName": "Clinic Name *",
    "forClinics.clinicNamePlaceholder": "e.g. Sunrise Family Clinic",
    "forClinics.contactPerson": "Contact Person Name *",
    "forClinics.contactPersonPlaceholder": "Your full name",
    "forClinics.phone": "Phone / WhatsApp Number *",
    "forClinics.phonePlaceholder": "+65 9123 4567",
    "forClinics.clinicType": "Clinic Type *",
    "forClinics.clinicTypePlaceholder": "Select clinic type",
    "forClinics.website": "Website / Booking Link (optional)",
    "forClinics.submitting": "Submitting...",
    "forClinics.submitRequest": "Submit Request",
    "forClinics.reviewNote": "We will review your request and reach out to you shortly.",
    "forClinics.alliedHealth": "Allied Health",
    "forClinics.mentalHealth": "Mental Health",
    "forClinics.others": "Others",

    // Marketplace CTA
    "marketplace.ctaTitle": "Reduce front desk interruptions.\nManage walk-ins more efficiently.",
    "marketplace.ctaDesc": "Let patients check queue load before arriving and reduce repeated \"how long\" questions — works alongside your existing workflow.",
    "marketplace.ctaBullet1": "Reduce repeated queue questions",
    "marketplace.ctaBullet2": "Let patients check before arriving",
    "marketplace.ctaBullet3": "No system replacement required",
    "marketplace.ctaSuitable": "Suitable for clinics with regular walk-ins or queue congestion.",
    "marketplace.ctaButton": "Submit Clinic Request",
    "marketplace.ctaReview": "We review each request to ensure fit.",

    // Managed Care Modal
    "managedCare.title": "Request Managed Care Support",
    "managedCare.badge": "Managed Care Pathway",
    "managedCare.conditionLabel": "Condition / Concern *",
    "managedCare.conditionPlaceholder": "e.g. Knee pain, skin rash",
    "managedCare.locationLabel": "Preferred Location",
    "managedCare.locationPlaceholder": "e.g. Central, East Singapore",
    "managedCare.timingLabel": "Preferred Appointment Timing",
    "managedCare.timingPlaceholder": "e.g. Weekday mornings, ASAP",
    "managedCare.urgencyLabel": "Urgency Level *",
    "managedCare.urgent": "Urgent",
    "managedCare.soon": "Soon",
    "managedCare.flexible": "Flexible",
    "managedCare.nameLabel": "Name *",
    "managedCare.namePlaceholder": "Your full name",
    "managedCare.contactLabel": "Contact Number *",
    "managedCare.contactPlaceholder": "e.g. +6591234567",
    "managedCare.submitButton": "Submit Request",
    "managedCare.submitting": "Submitting...",
    "managedCare.fillRequired": "Please fill in Name, Contact Number and Condition/Concern",
    "managedCare.invalidContact": "Please enter a valid contact number",
    "managedCare.submitFailed": "Failed to submit request. Please try again.",
    "managedCare.requestReceived": "Request Received",
    "managedCare.requestReceivedDesc": "Your request has been received. A care coordinator will review your case and contact you shortly to recommend the most suitable provider.",
    "managedCare.caseReference": "Case Reference",
    "managedCare.chatCoordinator": "Chat with Care Coordinator",

    // Service Intake Modal
    "serviceIntake.enquire": "Enquire",
    "serviceIntake.fullName": "Full Name *",
    "serviceIntake.fullNamePlaceholder": "Your full name",
    "serviceIntake.mobileNumber": "Mobile Number *",
    "serviceIntake.mobilePlaceholder": "e.g. +6591234567",
    "serviceIntake.mobileHint": "8-15 digits, country code optional",
    "serviceIntake.additionalNotes": "Additional Notes",
    "serviceIntake.additionalNotesPlaceholder": "Any other details...",
    "serviceIntake.pleaseNote": "Please Note",
    "serviceIntake.agreeCheckbox": "I understand and agree",
    "serviceIntake.submitting": "Submitting...",
    "serviceIntake.submitEnquiry": "Submit Enquiry",
    "serviceIntake.fillRequired": "Please fill in all required fields",
    "serviceIntake.invalidContact": "Please enter a valid contact number",
    "serviceIntake.submitFailed": "Failed to submit. Please try again.",
    "serviceIntake.enquiryReceived": "Enquiry Received",
    "serviceIntake.enquiryReceivedDesc": "Your enquiry has been recorded. Continue via WhatsApp to connect directly.",
    "serviceIntake.caseId": "Case ID",
    "serviceIntake.name": "Name",
    "serviceIntake.service": "Service",
    "serviceIntake.copyCaseId": "Copy Case ID",
    "serviceIntake.caseIdCopied": "Case ID copied!",
    "serviceIntake.continueWhatsApp": "Continue via WhatsApp",

    // Search Filters categories
    "search.category.all": "All Clinics",
    "search.category.gp_specialist": "GP & Specialist Care",
    "search.category.dental": "Dental Care",
    "search.category.therapy_rehab": "Therapy & Rehab",
    "search.category.mental_wellness": "Mental Wellness",
    "search.category.traditional_medicine": "Traditional Medicine",

    // GP, TCM, Wellness page titles
    "gpClinics.title": "Book a GP Appointment",
    "gpClinics.subtitle": "Find trusted general practitioners near you with real-time availability and digital queue management.",
    "tcmClinics.title": "Find Trusted TCM Clinics",
    "tcmClinics.subtitle": "Discover experienced Traditional Chinese Medicine practitioners for acupuncture, herbal medicine, and holistic care.",
    "wellnessClinics.title": "Wellness & Health Services",
    "wellnessClinics.subtitle": "Explore wellness centers, spas, and holistic health services to support your wellbeing journey.",

    // ContinuityServices
    "continuity.explore": "Explore",

    // ClinicCard queue link
    "clinicCard.saveQueueLink": "Save your queue link",
    "clinicCard.queueLinkCopied": "Queue link copied!",
    "clinicCard.peopleAhead": "People Ahead",
    "clinicCard.checkInCode": "Check-in Code",
  },
  zh: {
    // Navbar
    "nav.findClinics": "寻找诊所",
    "nav.staffDashboard": "员工仪表板",
    "nav.myAppointments": "我的预约",
    "nav.healthAssistant": "健康助手",
    "nav.analytics": "分析",
    "nav.signOut": "登出",
    "nav.login": "登录",
    "nav.signUp": "注册",
    "nav.menu": "菜单",
    "nav.help": "帮助与支持",
    "nav.restartTour": "重新开始导览",
    "nav.consultants": "健康顾问",
    
    // Continuity & Support Services
    "continuity.badge": "延续与支持",
    "continuity.title": "延续与支持服务",
    "continuity.subtitle": "超越诊所——支持您医疗旅程每个阶段的服务。",
    "continuity.speakers.title": "医疗演讲者与培训师",
    "continuity.speakers.desc": "联系经验丰富的医疗教育者和培训师，参加研讨会、讲座和专业发展活动。",
    "continuity.afterlife.title": "身后服务",
    "continuity.afterlife.desc": "为临终规划、丧亲辅导和纪念服务提供贴心的支持与指导。",
    "continuity.endOfService.title": "企业与社区健康",
    "continuity.endOfService.desc": "职场健康计划、健康检查及协调的健康促进活动。",
    "continuity.comingSoon": "即将推出",

    // Featured Consultants
    "featuredConsultants.badge": "管理式医疗",
    "featuredConsultants.title": "不确定从哪里开始？",
    "featuredConsultants.subtitle": "通过我们的管理式医疗服务提供商，获得合适的医疗指导。",
    "featuredConsultants.viewAll": "查看所有服务提供商",
    
    // Hero
    "hero.badge": "查看排队 • 预约 • 连接",
    "hero.title1": "出发前",
    "hero.title2": "先了解",
    "hero.subtitle": "在决定去哪里之前，先查看排队、可用性和附近的护理选项。",
    "hero.trustLine": "",
    "hero.findClinics": "查看附近诊所",
    "hero.findMyQueue": "查看我的排队状态",
    "hero.learnMore": "了解更多",
    "hero.queueTitle": "排队可见",
    "hero.queueDesc": "到达前查看预计排队状况",
    "hero.bookTitle": "预约",
    "hero.bookDesc": "所有诊所的即时预约",
    "hero.connectTitle": "连接",
    "hero.connectDesc": "AI健康助手和支持",
    "hero.activityTitle": "🟢 实时排队动态",
    "hero.activityDesc": "多家诊所正在更新中",
    
    // Features
    "features.badge": "功能特色",
    "features.title": "患者可以在ClynicQ上做什么",
    "features.subtitle": "",
    "features.queue.title": "排队可见",
    "features.queue.subtitle": "",
    "features.queue.description": "加入前查看前面有多少患者。",
    "features.book.title": "预约或联系",
    "features.book.subtitle": "",
    "features.book.description": "使用诊所的预约或联系流程，无需安装额外应用。",
    "features.connect.title": "引导护理支持",
    "features.connect.subtitle": "",
    "features.connect.description": "如果您不确定从哪里开始，请求引导到合适的医疗服务提供者。",
    "features.secondary1.title": "医师简介",
    "features.secondary2.title": "附近选项",
    "features.secondary3.title": "多诊所发现",
    
    // Queue Page
    "queue.title": "排队状况",
    "queue.loading": "加载排队信息中...",
    "queue.inQueue": "排队中",
    "queue.estWait": "预计等待",
    "queue.enableNotifications": "快轮到您时收到通知",
    "queue.notificationDesc": "我们会提醒您，方便您安排到达时间",
    "queue.complete": "咨询完成！",
    "queue.thankYou": "感谢您的光临",
    "queue.rateVisit": "评价您的就诊",
    "queue.feedbackThanks": "感谢您的反馈！",
    "queue.feedbackHelps": "您的反馈帮助我们改进服务",
    "queue.returnHome": "返回首页",
    "queue.bookAgain": "再次预约",
    "queue.beingServedNow": "正在为您服务！",
    "queue.proceedToConsultation": "请前往咨询区",
    "queue.yourQueueNumber": "您的排队号码",
    "queue.checkedIn": "您在排队中！",
    "queue.updated": "更新于",
    "queue.ago": "前",
    "queue.queueNumber": "排队号码",
    "queue.status": "状态",
    "queue.waiting": "等待中",
    "queue.estWaitTime": "预计等待",
    "queue.visitType": "就诊类型",
    "queue.peopleAhead": "前面的人数",
    "queue.generalConsultation": "一般咨询",
    "queue.notifiedWhenTurn": "快轮到您时我们会通知您",
    "queue.leaveQueue": "离开排队",
    "queue.checkIn": "签到",
    "queue.joinQueue": "加入排队",
    "queue.notificationsOn": "通知已开启",
    "queue.enableAlerts": "启用提醒",
    "queue.minutes": "分钟",
    "queue.disclaimer.title": "加入前请了解",
    "queue.disclaimer.bullet1": "排队顺序由诊所工作人员管理，可能会发生变化。",
    "queue.disclaimer.bullet2": "前方患者人数是实时运营指南，而非保证的等待时间。",
    "queue.disclaimer.bullet3": "紧急情况、临时到访或诊所优先安排可能影响排队进度。",
    "queue.disclaimer.bullet4": "如果您错过了您的号码，将按诊所政策处理。",
    "queue.disclaimer.understand": "我了解了",
    "queue.queueShiftNotice": "诊所已更新排队。您的预计位置已调整。",
    "queue.preConsult.title": "咨询前信息",
    "queue.preConsult.visitReason": "就诊原因",
    "queue.preConsult.visitReasonPlaceholder": "请描述您的症状或就诊原因...",
    "queue.preConsult.visitType": "就诊类型",
    "queue.preConsult.continue": "继续",
    "queue.smsConfirmation": "保存排队链接，随时查看最新状态",
    
    // Staff Dashboard
    "staff.title": "员工仪表板",
    "staff.loading": "加载员工仪表板中...",
    "staff.queueStatus": "队列状态：",
    "staff.open": "开放",
    "staff.closed": "关闭",
    "staff.totalToday": "今日总数",
    "staff.waiting": "等待中",
    "staff.served": "已服务",
    "staff.avgWait": "平均等待",
    "staff.currentQueue": "当前队列",
    "staff.managePatients": "管理排队等候的患者",
    "staff.callNextPatient": "呼叫下一位患者",
    "staff.noPatients": "队列中没有患者",
    "staff.queueEmpty": "队列目前为空",
    "staff.patient": "患者",
    "staff.waitingTime": "等待：",
    "staff.minutes2": "分钟",
    "staff.callPatient": "呼叫患者",
    "staff.markServed": "标记已服务",
    "staff.cancel": "取消",
    "staff.noShow": "未出现",
    "staff.moveUp": "上移",
    "staff.moveDown": "下移",
    "staff.addWalkIn": "添加上门患者",
    "staff.walkInName": "患者姓名",
    "staff.walkInPhone": "电话号码",
    "staff.walkInNamePlaceholder": "输入患者姓名",
    "staff.walkInPhonePlaceholder": "+65 XXXX XXXX",
    "staff.walkInAdded": "上门患者已添加到队列",
    
    // Footer
    "footer.tagline": "帮助您规划诊所就诊，减少等待",
    "footer.forPatients": "患者服务",
    "footer.findClinics": "寻找诊所",
    "footer.howItWorks": "工作原理",
    "footer.faq": "常见问题",
    "footer.forClinics": "诊所服务",
    "footer.joinPlatform": "加入平台",
    "footer.features": "功能特色",
    "footer.pricing": "价格",
    "footer.company": "公司",
    "footer.aboutUs": "关于我们",
    "footer.privacyPolicy": "隐私政策",
    "footer.termsOfService": "服务条款",
    "footer.copyright": "© 2024 ClynicQ. 符合PDPA的医疗保健平台。",
    
    // Appointments Page
    "appointments.title": "我的预约",
    "appointments.bookNew": "预约新时段",
    "appointments.reason": "原因",
    "appointments.noAppointments": "暂无预约",
    "appointments.browseClinics": "浏览诊所",
    "appointments.loading": "加载中...",
    "appointments.failedToLoad": "加载预约失败",
    "appointments.signInRequired": "请登录以查看预约",
    
    // Analytics Page
    "analytics.title": "分析仪表板",
    "analytics.phase4": "阶段4 - 数据洞察",
    "analytics.overview": "最近30天概览",
    "analytics.operationalTrends": "运营趋势",
    "analytics.totalPatients": "总患者数",
    "analytics.queueEntries": "队列记录",
    "analytics.avgWaitTime": "平均等待时间",
    "analytics.perPatient": "每位患者",
    "analytics.appointments": "预约",
    "analytics.booked": "已预约",
    "analytics.noShowRate": "未出现率",
    "analytics.noShows": "未出现",
    "analytics.behaviorSignals": "患者行为信号",
    "analytics.bookingPatterns": "预约模式",
    "analytics.bookingQuestion": "患者提前多久预约？",
    "analytics.avgBookingWindow": "平均预约窗口",
    "analytics.days": "天",
    "analytics.returnPatientRate": "回访患者率",
    "analytics.peakActivity": "高峰活动",
    "analytics.commonPatterns": "最常见的预约模式",
    "analytics.patients": "患者",
    "analytics.performanceBenchmark": "绩效基准",
    "analytics.comparePerformance": "比较您诊所的表现随时间的变化",
    "analytics.queueEfficiency": "队列效率",
    "analytics.waitTimeVsStandard": "平均等待时间与行业标准",
    "analytics.excellent": "优秀",
    "analytics.needsImprovement": "需要改进",
    "analytics.patientRetention": "患者保留",
    "analytics.returnRateVsAverage": "回访患者率与行业平均",
    "analytics.aboveAverage": "高于平均",
    "analytics.average": "平均",
    "analytics.attendanceRate": "出勤率",
    "analytics.noShowVsBenchmark": "未出现率与行业基准",
    "analytics.needsAttention": "需要关注",
    "analytics.loadingAnalytics": "加载分析中...",
    "analytics.accessDenied": "拒绝访问。仅诊所员工可查看分析。",
    
    // Booking Page
    "booking.title": "预约",
    "booking.selectDoctor": "选择医生（可选）",
    "booking.anyDoctor": "任何可用的医生",
    "booking.selectDate": "选择日期",
    "booking.selectTime": "选择时间",
    "booking.reasonForVisit": "就诊原因",
    "booking.reasonPlaceholder": "简要描述您的症状或就诊原因...",
    "booking.cancel": "取消",
    "booking.confirmBooking": "确认预约",
    "booking.booking": "预约中...",
    "booking.signInRequired": "请登录以预约",
    "booking.selectDateTime": "请选择日期和时间",
    "booking.bookingSuccess": "预约成功！",
    "booking.failedToLoad": "加载诊所信息失败",
    "booking.bookingFailed": "预约失败",
    "booking.loading": "加载中...",
    
    // Chatbot Page
    "chatbot.title": "健康助手",
    "chatbot.subtitle": "问我任何关于您健康的问题",
    "chatbot.placeholder": "输入您的消息...",
    "chatbot.disclaimer": "这是一个AI助手。请始终咨询医疗保健专业人员以获取医疗建议。",
    "chatbot.welcome": "您好！我是您的ClynicQ健康助手。我可以帮助您：\n\n• 症状评估\n• 健康建议\n• 预约准备\n• 咨询后护理\n\n我今天能为您提供什么帮助？",
    "chatbot.errorMessage": "抱歉，我遇到了错误。请重试。",
    "chatbot.failedToSend": "发送消息失败",
    
    // Dashboard Page
    "dashboard.title": "诊所仪表板",
    "dashboard.todayAppointments": "今日预约",
    "dashboard.inQueue": "队列中",
    "dashboard.pendingApproval": "待批准",
    "dashboard.totalUpcoming": "即将到来的总数",
    "dashboard.appointments": "预约",
    "dashboard.queue": "队列",
    "dashboard.plugins": "插件",
    "dashboard.confirm": "确认",
    "dashboard.decline": "拒绝",
    "dashboard.noUpcoming": "无即将到来的预约",
    "dashboard.noOneInQueue": "队列中无人",
    "dashboard.loading": "加载中...",
    "dashboard.accessDenied": "您无权访问仪表板",
    "dashboard.noClinic": "您的账户未分配诊所",
    "dashboard.failedToLoad": "加载仪表板数据失败",
    "dashboard.confirmed": "已确认",
    "dashboard.cancelled": "已取消",
    "dashboard.estWait": "预计等待",
    "dashboard.walkIn": "步入患者",
    
    // Auth Page
    "auth.welcomeBack": "欢迎回来",
    "auth.enterCredentials": "输入您的凭据以访问您的账户",
    "auth.createAccount": "创建账户",
    "auth.signupDescription": "注册以开始预约",
    "auth.email": "邮箱",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "密码",
    "auth.fullName": "全名",
    "auth.namePlaceholder": "张三",
    "auth.confirmPassword": "确认密码",
    "auth.signIn": "登录",
    "auth.login": "登录",
    "auth.signup": "注册",
    "auth.termsAgreement": "继续即表示您同意我们的服务条款和隐私政策",
    "auth.invalidEmail": "无效的邮箱地址",
    "auth.passwordLength": "密码必须至少6个字符",
    "auth.passwordMismatch": "密码不匹配",
    "auth.nameTooShort": "姓名必须至少2个字符",
    
    // NotFound Page
    "notFound.title": "404",
    "notFound.message": "哎呀！页面未找到",
    "notFound.returnHome": "返回主页",
    
    // ClinicCard
    "clinicCard.open": "开放",
    "clinicCard.closed": "关闭",
    "clinicCard.inQueue": "排队中",
    "clinicCard.people": "人",
    "clinicCard.estWait": "预计等待",
    "clinicCard.youreInQueue": "您在排队中",
    "clinicCard.position": "位置",
    "clinicCard.of": "共",
    "clinicCard.waiting": "等待中",
    "clinicCard.checkIn": "签到",
    "clinicCard.leaveQueue": "离开排队",
    "clinicCard.readyToSkip": "查看排队",
    "clinicCard.joinVirtual": "查看前面有多少人",
    "clinicCard.visitType": "就诊类型",
    "clinicCard.generalConsultation": "一般咨询",
    "clinicCard.followUp": "复诊",
    "clinicCard.emergency": "急诊",
    "clinicCard.vaccination": "疫苗接种",
    "clinicCard.healthScreening": "健康检查",
    "clinicCard.joinQueue": "加入排队",
    "clinicCard.joining": "加入中...",
    "clinicCard.viewDetails": "查看详情",
    "clinicCard.queueSuccess": "您是排队中的第{number}号！保存链接随时查看。",
    "clinicCard.alreadyInQueue": "您已在此排队中！",
    "clinicCard.leftQueue": "成功离开排队",
    "clinicCard.failedToLeave": "离开排队失败",
    "clinicCard.checkedIn": "签到成功！",
    "clinicCard.signInRequired": "请登录以加入排队",
    "clinicCard.failedToJoin": "加入排队失败",
    "clinicCard.availabilitiesToday": "今日可预约时段",
    "clinicCard.servicesOffered": "提供的服务",
    "clinicCard.joinedQueue": "您已加入排队！保存链接随时查看。",
    
    // MarketplaceSection
    "marketplace.title": "寻找您的诊所",
    "marketplace.subtitle": "浏览附近的诊所，查看预计排队状况，规划您的就诊以减少等待",
    "marketplace.loading": "加载诊所中...",
    
    // SearchFilters
    "search.placeholder": "搜索诊所、医生或专科...",
    "search.location": "位置",
    "search.filters": "筛选",
    "search.all": "全部",
    "search.gp": "全科",
    "search.tcm": "中医",
    "search.wellness": "健康",
    "search.specialists": "专科",
    
    // QuickGuide
    "guide.welcome": "欢迎来到ClynicQ！👋",
    "guide.description": "您的出行前医疗保健伴侣。查看排队预估、预约就诊，并与新加坡各地的医疗服务连接。",
    "guide.quickLinks": "快速链接：",
    "guide.joinQueue": "查看排队",
    "guide.appointments": "预约",
    "guide.healthAssistant": "健康助手",
    "guide.analytics": "分析",
    "guide.minimize": "最小化",
    "guide.gotIt": "知道了！",
    "guide.quickGuide": "快速指南",
    
    // OnboardingTour
    "tour.welcomeTitle": "欢迎来到ClynicQ！👋",
    "tour.welcomeDesc": "查看排队 • 预约 • 连接医疗服务。'Q'徽章显示参与诊所的预计排队活动。",
    "tour.browseTitle": "浏览并查看排队 🏥",
    "tour.browseDesc": "查找诊所，查看预计排队状况，出发前规划就诊。",
    "tour.navTitle": "快速访问 🧭",
    "tour.navDesc": "使用菜单访问预约、健康助手和分析。",
    "tour.back": "返回",
    "tour.skip": "跳过",
    "tour.next": "下一步",
    "tour.gotIt": "知道了！",
    "tour.stepCount": "{current}/{total}",
    
    // MyClynicQPlugin
    "myclynicq.comingSoon": "即将推出",
    "myclynicq.title": "我的ClynicQ",
    "myclynicq.subtitle": "通过WhatsApp自动提醒和即时支持，不错过任何预约",
    "myclynicq.chatWhatsApp": "在WhatsApp上聊天",
    "myclynicq.alwaysAvailable": "您的健康助手，随时可用",
    "myclynicq.easyBooking": "轻松预约",
    "myclynicq.easyBookingDesc": "通过聊天预约、重新安排或取消预约",
    "myclynicq.smartReminders": "智能提醒",
    "myclynicq.smartRemindersDesc": "及时提醒，不会错过就诊",
    "myclynicq.instantAnswers": "即时回答",
    "myclynicq.instantAnswersDesc": "随时询问有关预约或诊所的问题",
    "myclynicq.queueUpdates": "队列更新",
    "myclynicq.queueUpdatesDesc": "无需致电诊所即可了解队列位置",
    "myclynicq.howItWorks": "工作原理",
    "myclynicq.step1": "在ClynicQ上预约",
    "myclynicq.step2": "在WhatsApp上收到确认消息",
    "myclynicq.step3": "在就诊前收到提醒",
    "myclynicq.step4": "随时与MyClynicQ聊天寻求帮助",
    "myclynicq.availableChannels": "可用渠道",
    "myclynicq.whatsapp": "WhatsApp",
    "myclynicq.sms": "短信",
    "myclynicq.webChat": "网页聊天",
    "myclynicq.stayConnected": "与您的医疗保健旅程保持联系。MyClynicQ让您随时了解情况，并使管理预约变得轻松。",
    
    // DoctorProfile
    "doctorProfile.loading": "正在加载医生资料...",
    "doctorProfile.notFound": "未找到医生",
    "doctorProfile.qualifications": "资质",
    "doctorProfile.languages": "语言",
    "doctorProfile.about": "关于",
    "doctorProfile.availability": "可预约时间",
    "doctorProfile.bookAppointment": "预约",
    "doctorProfile.viewClinic": "查看诊所",
    "doctorProfile.registration": "注册号",
    "doctorProfile.yearsExperience": "年经验",
    "doctorProfile.noQualifications": "无资质信息",
    "doctorProfile.noLanguages": "无语言信息",
    "doctorProfile.closed": "休息",
    
    // ClinicProfile
    "clinicProfile.bookAppointment": "预约挂号",
    "clinicProfile.joinQueue": "加入排队",
    "clinicProfile.clinicPhotos": "诊所照片",
    "clinicProfile.photoGalleryComingSoon": "照片库即将推出",
    "clinicProfile.phone": "电话",
    "clinicProfile.email": "电邮",
    "clinicProfile.notAvailable": "暂无",
    "clinicProfile.currentQueue": "当前排队",
    "clinicProfile.waiting": "等待中",
    "clinicProfile.doctors": "医生",
    "clinicProfile.awards": "奖项",
    "clinicProfile.operatingHours": "营业时间",
    "clinicProfile.reviews": "评价",
    "clinicProfile.verified": "已认证",
    "clinicProfile.yearsExperience": "年经验",
    "clinicProfile.qualifications": "资历与证书",
    "clinicProfile.noDoctorsAvailable": "暂无医生信息",
    "clinicProfile.awardsRecognition": "奖项与荣誉",
    "clinicProfile.awardedIn": "获奖年份",
    "clinicProfile.awardsComingSoon": "奖项和荣誉将在此显示",
    "clinicProfile.noReviews": "暂无评价",
    "clinicProfile.anonymous": "匿名用户",
    "clinicProfile.loading": "加载中...",
    "clinicProfile.signInToBook": "请登录以预约",
    "clinicProfile.failedToLoad": "无法加载诊所信息",
    "clinicProfile.requestManagedCare": "申请管理式医疗支持",
    "clinicProfile.managedCareSubtitle": "NMG 将协调您的预约并尽快与您联系。",
    "clinicProfile.fieldName": "姓名",
    "clinicProfile.fieldPhone": "电话号码",
    "clinicProfile.fieldTiming": "首选时间",
    "clinicProfile.fieldConcern": "简要描述",
    "clinicProfile.fieldTimingPlaceholder": "例如：工作日上午",
    "clinicProfile.fieldConcernPlaceholder": "简要描述您的问题",
    "clinicProfile.submitRequest": "提交请求",
    "clinicProfile.submitting": "提交中...",
    "clinicProfile.requestReceived": "请求已收到。NMG 将尽快与您联系。",
    
    // Consultant Section
    "consultant.badge": "专业指导",
    "consultant.pageTitle": "管理式医疗服务提供商",
    "consultant.pageDescription": "不确定选择哪家诊所？我们值得信赖的管理式医疗服务提供商将为您推荐合适的医疗服务。",
    "consultant.searchPlaceholder": "按姓名或专业搜索...",
    "consultant.feature1Title": "个性化指导",
    "consultant.feature1Desc": "为您匹配合适的医疗服务",
    "consultant.feature2Title": "值得信赖的专家",
    "consultant.feature2Desc": "经过认证的医疗保健专业人员",
    "consultant.feature3Title": "免费咨询",
    "consultant.feature3Desc": "无任何义务或压力",
    "consultant.noResults": "未找到顾问",
    "consultant.noResultsDesc": "请尝试调整您的搜索条件",
    "consultant.viewProfile": "查看资料",
    "consultant.notFound": "未找到顾问",
    "consultant.backToList": "返回顾问列表",
    "consultant.getGuidance": "获取指导",
    "consultant.about": "关于",
    "consultant.services": "提供的服务",
    "consultant.patientTypes": "服务的患者类型",
    "consultant.needHelp": "需要帮助决定？",
    "consultant.needHelpDesc": "直接与此顾问交流，获取个性化建议。",
    "consultant.speakToConsultant": "联系顾问",
    "consultant.recommendedClinics": "推荐诊所",
    "consultant.recommendedBy": "由 {name} 推荐",
    
    // Admin Consultants
    "admin.consultantsTitle": "管理顾问",
    "admin.consultantsDesc": "添加、编辑和管理医疗服务提供商",
    "admin.addConsultant": "添加顾问",
    "admin.editConsultant": "编辑顾问",
    "admin.name": "姓名",
    "admin.namePlaceholder": "输入顾问姓名",
    "admin.title": "职称",
    "admin.titlePlaceholder": "例如：健康顾问",
    "admin.photoUrl": "照片链接",
    "admin.shortBio": "简介",
    "admin.shortBioPlaceholder": "简短描述（2-3行）",
    "admin.fullBio": "详细介绍",
    "admin.fullBioPlaceholder": "详细的背景和经验",
    "admin.areasOfFocus": "专注领域",
    "admin.addAreaPlaceholder": "例如：疼痛管理",
    "admin.servicesOffered": "提供的服务",
    "admin.addServicePlaceholder": "例如：健康评估",
    "admin.patientTypes": "患者类型",
    "admin.addPatientTypePlaceholder": "例如：慢性疼痛患者",
    "admin.active": "活跃",
    "admin.inactive": "未激活",
    "admin.update": "更新",
    "admin.create": "创建",
    "admin.recommendedClinics": "推荐诊所",
    "admin.addClinic": "添加诊所",
    "admin.noConsultants": "暂无顾问",
    "admin.noConsultantsDesc": "添加您的第一位医疗服务提供商以开始",
    "admin.nameRequired": "姓名为必填项",
    "admin.updateError": "更新顾问失败",
    "admin.createError": "创建顾问失败",
    "admin.consultantUpdated": "顾问更新成功",
    "admin.consultantCreated": "顾问创建成功",

    // Organization (NYMG)
    "org.name": "南洋医疗集团",
    "org.subtitle": "管理式医疗服务提供商",
    "org.tagline": "整合式医疗网络，跨多学科提供协调的患者护理。",
    "org.highlight1": "多诊所网络",
    "org.highlight2": "全科与专科护理",
    "org.highlight3": "协调护理路径",
    "org.viewProvider": "查看提供商",
    "org.heroIntro": "南洋医疗集团是一家管理式医疗服务提供商，提供跨全科、专科和联合健康服务的协调护理。",
    "org.startConsultation": "开始咨询",
    "org.viewServices": "查看服务",
    "org.aboutTitle": "关于南洋医疗集团",
    "org.aboutBody": "南洋医疗集团作为一个综合医疗生态系统运营，支持患者跨多个护理接触点。通过协调的工作流程和结构化的提供者网络，患者从就诊到治疗和随访都能获得无缝引导。",
    "org.howItWorksTitle": "工作原理",
    "org.stepLabel": "步骤",
    "org.step1Title": "提交申请表",
    "org.step1Desc": "患者填写结构化的申请表。",
    "org.step2Title": "匹配与协调",
    "org.step2Desc": "分配合适的医疗礼宾或提供者。",
    "org.step3Title": "直接跟进",
    "org.step3Desc": "通过WhatsApp继续对话，快速响应。",
    "org.conciergeTitle": "医疗礼宾团队",
    "org.connect": "联系",
    "org.noConcierges": "暂无礼宾资料。",
    "org.servicesTitle": "服务概览",
    "org.service.general": "全科咨询",
    "org.service.chronic": "慢性病护理",
    "org.service.specialist": "专科转介",
    "org.service.preventive": "预防保健",
    "org.heroDesc": "跨全科、专科护理和转介服务的患者访问——通过单一网络管理。",
    "org.oneEntry": "一站入口",
    "org.weMatchYou": "为您匹配",
    "org.weFollowUp": "跟进服务",
    "org.networkCapabilities": "网络能力",
    "org.clinicNetwork": "诊所网络",
    "org.specialistAccess": "专科通道",
    "org.coverageSupport": "保障支持",
    "org.whyConciergeTitle": "为什么需要医疗礼宾服务",
    "org.whyConciergeDesc": "医疗保健不是一个单一系统——患者常常需要自己在多个提供者、转介和步骤之间穿梭。",
    "org.whyConciergeSimplifies": "这种模式简化了流程：",
    "org.whyConcierge.oneIntake": "一次填写",
    "org.whyConcierge.guidedMatching": "引导匹配",
    "org.whyConcierge.continuousFollowUp": "持续跟进",
    "org.careComparison": "护理体验对比",
    "org.unstructured": "无结构",
    "org.unstructured.multipleEntry": "多个入口",
    "org.unstructured.noProvider": "无明确选择",
    "org.unstructured.manualCoord": "手动协调",
    "org.unstructured.fragmented": "碎片化护理",
    "org.nanyangModel": "南洋模式",
    "org.nanyang.singleEntry": "单一入口",
    "org.nanyang.guidedMatching": "引导匹配",
    "org.nanyang.structuredHandoff": "结构化交接",
    "org.nanyang.continuousCare": "持续护理",
    "org.intakeFlowTitle": "患者申请流程",
    "org.intakeStep1": "提交您的病情或关注事项",
    "org.intakeStep2": "匹配到合适的医疗提供者",
    "org.intakeStep3": "通过WhatsApp即时继续",
    "org.intakeNote": "无需下载应用。您直接向诊所付款——无额外费用。",
    "org.exampleIntakePreview": "示例申请预览",
    "org.fakeField.condition": "病情/关注事项",
    "org.fakeField.conditionVal": "慢性背痛管理",
    "org.fakeField.location": "首选地点",
    "org.fakeField.locationVal": "中部/东部",
    "org.fakeField.urgency": "紧急程度",
    "org.fakeField.urgencyVal": "尽快",
    "org.fakeField.contact": "联系方式",
    "org.availableCareAreas": "可用护理领域",
    "org.carePathways": "护理路径",
    "org.careCoordTeam": "护理协调团队",
    "org.careCoordDesc": "每位协调员引导您从申请到合适的护理提供者。",
    "org.active": "在线",
    "org.start": "开始",
    "org.noConciergesAvailable": "目前没有可用的礼宾。",
    "org.multiClinic": "多诊所",
    "org.patientFlow": "患者流程",
    "org.careDelivery": "护理交付",
    "org.howCareCoordWorks": "护理协调如何运作",
    "org.howStep1": "提交申请",
    "org.howStep1Desc": "结构化护理请求表",
    "org.howStep2": "病例匹配",
    "org.howStep2Desc": "分配到合适的提供者",
    "org.howStep3": "通过WhatsApp跟进",
    "org.howStep3Desc": "即时患者响应",

    // SHA
    "sha.badge": "专科医生团队",
    "sha.name": "新加坡医疗保健联盟",
    "sha.heroDesc": "在新加坡获取跨多个学科的广泛专科医生团队。",
    "sha.multipleHospitals": "多家医院",
    "sha.whatsappContact": "WhatsApp联系",
    "sha.hospitalLocations": "医院位置",
    "sha.specialistDisciplines": "专科学科",
    "sha.specialistDesc": "可用的专科学科包括外科、内科和跨多个领域的亚专科护理。",
    "sha.keyProcedures": "主要手术与服务",
    "sha.procedure1": "结肠镜和胃镜检查",
    "sha.procedure2": "胃袖手术",
    "sha.procedure3": "疝气修复",
    "sha.procedure4": "前列腺手术",
    "sha.procedure5": "乳房活检和乳腺癌手术",
    "sha.procedure6": "扁桃体和腺样体手术",
    "sha.findSpecialist": "找到您的专科医生",
    "sha.findSpecialistDesc": "通过WhatsApp或热线联系我们，与专科医生对接。",
    "sha.journeyStep1": "描述您的病情",
    "sha.journeyStep2": "通过WhatsApp联系",
    "sha.journeyStep3": "获得专科指导",
    "sha.startWithDr": "联系郭医生 →",
    "sha.noAppNeeded": "无需下载应用。直接通过WhatsApp联系。",
    "sha.intakeDesc": "描述您的病情，我们将为您连接到合适的专科医生。",
    "sha.exampleIntakePreview": "示例申请预览",
    "sha.fakeField.condition": "病情/关注事项",
    "sha.fakeField.conditionVal": "反复膝盖不适",
    "sha.fakeField.location": "首选地点",
    "sha.fakeField.locationVal": "西部/裕廊",
    "sha.fakeField.urgency": "紧急程度",
    "sha.fakeField.urgencyVal": "一周内",
    "sha.fakeField.contact": "联系方式",
    "sha.careCoordination": "护理协调",
    "sha.careCoordDesc": "由郭瑞强医生领导的护理协调。",
    "sha.noCoordinators": "目前没有可用的协调员。",
    "sha.availableCareAreas": "可用护理领域",
    "sha.carePathways": "护理路径",
    "sha.generalPractice": "全科诊疗",
    "sha.chronicDisease": "慢性疾病",
    "sha.specialistReferral": "专科转介",
    "sha.rehabilitation": "康复治疗",
    "sha.mentalWellness": "心理健康",
    "sha.active": "在线",
    "sha.start": "开始",

    // Speakers & Trainers
    "speakers.badge": "医疗演讲者与培训师",
    "speakers.title": "医疗演讲者与培训师",
    "speakers.desc": "联系经验丰富的医疗演讲者和培训师，参加企业健康、社区卫生和专业发展活动。",
    "speakers.expertSpeakers": "专业演讲者",
    "speakers.expertSpeakersDesc": "行业经验丰富的专业人士",
    "speakers.customProgrammes": "定制课程",
    "speakers.customProgrammesDesc": "为您的机构量身定制",
    "speakers.corporateCommunity": "企业与社区",
    "speakers.corporateCommunityDesc": "适用于工作场所和社区",

    // Speaker Profile (Ouch)
    "speakerProfile.badge": "医疗演讲者与培训师",
    "speakerProfile.heroDesc": "企业健康讲座、中医养生工作坊和医疗培训——由慧芳主讲。",
    "speakerProfile.enquire": "咨询",
    "speakerProfile.weCustomise": "定制方案",
    "speakerProfile.weDeliver": "现场交付",
    "speakerProfile.capabilities": "服务能力",
    "speakerProfile.tcmHealthTalks": "中医健康讲座",
    "speakerProfile.b2bWorkshops": "B2B & B2C 工作坊",
    "speakerProfile.corporateTraining": "企业培训",
    "speakerProfile.aboutUs": "关于我们",
    "speakerProfile.aboutDesc": "Ouch Pte Ltd 专注于中医教育和健康培训，服务企业（B2B）和消费者（B2C）群体。从企业健康日到社区健康活动，Ouch 提供引人入胜的工作坊和健康讲座，将传统智慧与现代养生相结合——涵盖压力管理、穴位自我保健、饮食疗法和整体健康。",
    "speakerProfile.leadSpeaker": "首席演讲者及中医教育者",
    "speakerProfile.huiFangBio": "慧芳是一位认证中医师和医疗教育者，在企业健康讲座和社区工作坊方面拥有多年经验。她专注于让中医概念对现代受众实用且易于理解。",
    "speakerProfile.tcmWorkshopsTag": "中医工作坊",
    "speakerProfile.corporateWellnessTag": "企业健康",
    "speakerProfile.healthEducationTag": "健康教育",
    "speakerProfile.connectWithHuiFang": "联系慧芳",
    "speakerProfile.howItWorks": "工作流程",
    "speakerProfile.step1": "提交您的询问或活动详情",
    "speakerProfile.step2": "获得定制方案提案",
    "speakerProfile.step3": "确认后我们现场交付",
    "speakerProfile.flexibility": "灵活安排。为您的受众量身定制内容——从企业团队到社区团体。",
    "speakerProfile.exampleEnquiry": "示例询问",
    "speakerProfile.fakeField.eventType": "活动类型",
    "speakerProfile.fakeField.eventTypeVal": "企业中医养生工作坊",
    "speakerProfile.fakeField.audience": "受众",
    "speakerProfile.fakeField.audienceVal": "50名员工，财务团队",
    "speakerProfile.fakeField.format": "形式",
    "speakerProfile.fakeField.formatVal": "B2B — 现场，90分钟",
    "speakerProfile.fakeField.contact": "联系方式",
    "speakerProfile.whyOuch": "为什么选择 Ouch Pte Ltd",
    "speakerProfile.whyOuchDesc": "医疗教育需要引人入胜、有循证基础，且与受众相关。",
    "speakerProfile.whatSetsUsApart": "我们的优势：",
    "speakerProfile.apart1": "中医专业知识",
    "speakerProfile.apart2": "B2B & B2C 课程",
    "speakerProfile.apart3": "针对您的行业定制",
    "speakerProfile.apart4": "互动且引人入胜的交付",
    "speakerProfile.experienceComparison": "体验对比",
    "speakerProfile.genericTalks": "通用讲座",
    "speakerProfile.generic1": "千篇一律",
    "speakerProfile.generic2": "无临床支持",
    "speakerProfile.generic3": "被动交付",
    "speakerProfile.generic4": "参与度低",
    "speakerProfile.ouchModel": "Ouch 模式",
    "speakerProfile.ouch1": "中医定制",
    "speakerProfile.ouch2": "循证基础",
    "speakerProfile.ouch3": "互动工作坊",
    "speakerProfile.ouch4": "可量化成果",
    "speakerProfile.availableProgrammes": "可用课程",
    "speakerProfile.serviceAreas": "服务领域",
    "speakerProfile.b2bCorporateWorkshops": "B2B 企业工作坊",
    "speakerProfile.b2cCommunitySessions": "B2C 社区课程",
    "speakerProfile.professionalTraining": "专业培训",
    "speakerProfile.readyToBook": "准备预约课程？",
    "speakerProfile.readyToBookDesc": "提交您的询问，我们将为您回复定制方案。",
    "speakerProfile.enquireNow": "立即咨询",

    // Afterlife Services page
    "afterlife.badge": "身后服务",
    "afterlife.title": "身后服务",
    "afterlife.desc": "为家庭提供有温度的临终规划、纪念服务和丧亲支持。",
    "afterlife.compassionateCare": "温情护理",
    "afterlife.compassionateCareDesc": "庄严且尊重的服务",
    "afterlife.prePlanning": "预先规划",
    "afterlife.prePlanningDesc": "可进行预先安排",
    "afterlife.familySupport": "家庭支持",
    "afterlife.familySupportDesc": "丧亲辅导与悲伤关怀",

    // Afterlife Profile (Nirvana)
    "afterlifeProfile.heroDesc": "为家庭提供全面的纪念规划、丧亲支持和有尊严的身后服务。",
    "afterlifeProfile.reachOut": "联系我们",
    "afterlifeProfile.weGuideYou": "指引方向",
    "afterlifeProfile.weSupport": "持续支持",
    "afterlifeProfile.enquireNow": "立即咨询",
    "afterlifeProfile.services": "服务",
    "afterlifeProfile.memorialServices": "纪念服务",
    "afterlifeProfile.prePlanning": "预先规划",
    "afterlifeProfile.bereavementSupport": "丧亲支持",
    "afterlifeProfile.aboutTitle": "关于 Nirvana",
    "afterlifeProfile.aboutP1": "Nirvana 是一家值得信赖的综合身后及纪念服务提供商。凭借对温情和尊严的深切承诺，Nirvana 帮助家庭度过临终规划、纪念安排和丧亲支持——确保每个家庭在困难时期都能获得应有的关怀和指导。",
    "afterlifeProfile.aboutP2": "从预先规划到即时安排，Nirvana 经验丰富的顾问团队在所有文化和宗教传统中提供个性化指导，使整个过程尽可能温和顺畅。",
    "afterlifeProfile.ourConsultants": "我们的顾问",
    "afterlifeProfile.connectWithAdvisor": "联系 Nirvana 顾问",
    "afterlifeProfile.connectDesc": "与经验丰富的顾问交谈，获得贴心的指导。",
    "afterlifeProfile.connect": "联系",
    "afterlifeProfile.howItWorks": "工作流程",
    "afterlifeProfile.howStep1": "告知您的需求或咨询事项",
    "afterlifeProfile.howStep2": "获得可用选项的指引",
    "afterlifeProfile.howStep3": "全程持续支持",
    "afterlifeProfile.howNote": "每一步都有温情指导。无压力——在您需要时提供支持。",
    "afterlifeProfile.startEnquiry": "开始咨询",
    "afterlifeProfile.exampleEnquiry": "示例咨询",
    "afterlifeProfile.fakeField.serviceType": "服务类型",
    "afterlifeProfile.fakeField.serviceTypeVal": "纪念规划",
    "afterlifeProfile.fakeField.arrangement": "偏好安排",
    "afterlifeProfile.fakeField.arrangementVal": "传统 / 现代",
    "afterlifeProfile.fakeField.timeline": "时间安排",
    "afterlifeProfile.fakeField.timelineVal": "灵活",
    "afterlifeProfile.fakeField.contact": "联系方式",
    "afterlifeProfile.whyNirvana": "为什么选择 Nirvana",
    "afterlifeProfile.whyNirvanaDesc": "临终规划值得获得尊严、温情和专业指导。",
    "afterlifeProfile.whatSetsUsApart": "我们的优势：",
    "afterlifeProfile.apart1": "值得信赖的知名提供商",
    "afterlifeProfile.apart2": "全面的服务范围",
    "afterlifeProfile.apart3": "以家庭为中心的方式",
    "afterlifeProfile.apart4": "多元文化敏感性",
    "afterlifeProfile.serviceComparison": "服务对比",
    "afterlifeProfile.withoutGuidance": "无指导",
    "afterlifeProfile.without1": "选择过多",
    "afterlifeProfile.without2": "流程不清",
    "afterlifeProfile.without3": "情绪负担",
    "afterlifeProfile.without4": "临时决定",
    "afterlifeProfile.nirvanaModel": "Nirvana 模式",
    "afterlifeProfile.nirvana1": "引导规划",
    "afterlifeProfile.nirvana2": "清晰流程",
    "afterlifeProfile.nirvana3": "情绪支持",
    "afterlifeProfile.nirvana4": "预先安排",
    "afterlifeProfile.needGuidance": "需要指导或支持？",
    "afterlifeProfile.needGuidanceDesc": "联系我们的团队，进行温情、无压力的对话。",

    // Afterlife Profile Agent data
    "afterlifeProfile.agent1.name": "Sarah Lim",
    "afterlifeProfile.agent1.title": "高级身后服务顾问",
    "afterlifeProfile.agent1.bio": "拥有超过10年经验，以温情和专业引导家庭进行纪念规划。",
    "afterlifeProfile.agent1.tag1": "纪念规划",
    "afterlifeProfile.agent1.tag2": "预先安排",
    "afterlifeProfile.agent1.tag3": "家庭支持",
    "afterlifeProfile.agent2.name": "David Tan",
    "afterlifeProfile.agent2.title": "丧亲支持顾问",
    "afterlifeProfile.agent2.bio": "专注于丧亲辅导，帮助家庭以关怀和敏感度度过临终决策。",
    "afterlifeProfile.agent2.tag1": "悲伤辅导",
    "afterlifeProfile.agent2.tag2": "文化服务",
    "afterlifeProfile.agent2.tag3": "遗产指导",
    "afterlifeProfile.agent3.name": "Michelle Wong",
    "afterlifeProfile.agent3.title": "预先规划专家",
    "afterlifeProfile.agent3.bio": "帮助个人和家庭进行预先规划，确保愿望得到记录和安排。",
    "afterlifeProfile.agent3.tag1": "预先规划",
    "afterlifeProfile.agent3.tag2": "文件办理",
    "afterlifeProfile.agent3.tag3": "财务规划",

    // For Clinics page
    "forClinics.thankYou": "谢谢！",
    "forClinics.thankYouDesc": "感谢，我们已收到您的请求。我们将尽快与您联系。",
    "forClinics.title": "在不改变现有系统的情况下改善患者流程",
    "forClinics.subtitle": "ClynicQ 帮助诊所减少前台中断、管理步入患者，并在患者到达前提供可见性。",
    "forClinics.bullet1": "减少重复的排队询问和前台中断",
    "forClinics.bullet2": "让患者在到达前查看排队情况",
    "forClinics.bullet3": "保持您现有的预约和诊所工作流程",
    "forClinics.clinicName": "诊所名称 *",
    "forClinics.clinicNamePlaceholder": "例如：日出家庭诊所",
    "forClinics.contactPerson": "联系人姓名 *",
    "forClinics.contactPersonPlaceholder": "您的全名",
    "forClinics.phone": "电话 / WhatsApp号码 *",
    "forClinics.phonePlaceholder": "+65 9123 4567",
    "forClinics.clinicType": "诊所类型 *",
    "forClinics.clinicTypePlaceholder": "选择诊所类型",
    "forClinics.website": "网站 / 预约链接（可选）",
    "forClinics.submitting": "提交中...",
    "forClinics.submitRequest": "提交请求",
    "forClinics.reviewNote": "我们将审核您的请求并尽快与您联系。",
    "forClinics.alliedHealth": "联合健康",
    "forClinics.mentalHealth": "心理健康",
    "forClinics.others": "其他",

    // Marketplace CTA
    "marketplace.ctaTitle": "减少前台中断。\n更高效地管理步入患者。",
    "marketplace.ctaDesc": "让患者在到达前查看排队情况，减少重复的"还要多久"问题——与您现有的工作流程兼容。",
    "marketplace.ctaBullet1": "减少重复的排队询问",
    "marketplace.ctaBullet2": "让患者在到达前查看",
    "marketplace.ctaBullet3": "无需更换系统",
    "marketplace.ctaSuitable": "适合有常规步入患者或排队拥堵的诊所。",
    "marketplace.ctaButton": "提交诊所请求",
    "marketplace.ctaReview": "我们审核每个请求以确保适合。",

    // Managed Care Modal
    "managedCare.title": "申请管理式护理支持",
    "managedCare.badge": "管理式护理路径",
    "managedCare.conditionLabel": "病情/关注事项 *",
    "managedCare.conditionPlaceholder": "例如：膝盖疼痛、皮疹",
    "managedCare.locationLabel": "首选地点",
    "managedCare.locationPlaceholder": "例如：中部、新加坡东部",
    "managedCare.timingLabel": "首选预约时间",
    "managedCare.timingPlaceholder": "例如：工作日上午、尽快",
    "managedCare.urgencyLabel": "紧急程度 *",
    "managedCare.urgent": "紧急",
    "managedCare.soon": "尽快",
    "managedCare.flexible": "灵活",
    "managedCare.nameLabel": "姓名 *",
    "managedCare.namePlaceholder": "您的全名",
    "managedCare.contactLabel": "联系电话 *",
    "managedCare.contactPlaceholder": "例如：+6591234567",
    "managedCare.submitButton": "提交请求",
    "managedCare.submitting": "提交中...",
    "managedCare.fillRequired": "请填写姓名、联系电话和病情/关注事项",
    "managedCare.invalidContact": "请输入有效的联系电话",
    "managedCare.submitFailed": "提交失败，请重试。",
    "managedCare.requestReceived": "请求已收到",
    "managedCare.requestReceivedDesc": "您的请求已收到。护理协调员将审核您的案例并尽快与您联系，推荐最合适的提供者。",
    "managedCare.caseReference": "案例编号",
    "managedCare.chatCoordinator": "与护理协调员聊天",

    // Service Intake Modal
    "serviceIntake.enquire": "咨询",
    "serviceIntake.fullName": "全名 *",
    "serviceIntake.fullNamePlaceholder": "您的全名",
    "serviceIntake.mobileNumber": "手机号码 *",
    "serviceIntake.mobilePlaceholder": "例如：+6591234567",
    "serviceIntake.mobileHint": "8-15位数字，国家代码可选",
    "serviceIntake.additionalNotes": "补充说明",
    "serviceIntake.additionalNotesPlaceholder": "其他详细信息...",
    "serviceIntake.pleaseNote": "请注意",
    "serviceIntake.agreeCheckbox": "我理解并同意",
    "serviceIntake.submitting": "提交中...",
    "serviceIntake.submitEnquiry": "提交咨询",
    "serviceIntake.fillRequired": "请填写所有必填项",
    "serviceIntake.invalidContact": "请输入有效的联系电话",
    "serviceIntake.submitFailed": "提交失败，请重试。",
    "serviceIntake.enquiryReceived": "咨询已收到",
    "serviceIntake.enquiryReceivedDesc": "您的咨询已记录。通过WhatsApp继续直接联系。",
    "serviceIntake.caseId": "案例编号",
    "serviceIntake.name": "姓名",
    "serviceIntake.service": "服务",
    "serviceIntake.copyCaseId": "复制案例编号",
    "serviceIntake.caseIdCopied": "案例编号已复制！",
    "serviceIntake.continueWhatsApp": "通过WhatsApp继续",

    // Search Filters categories
    "search.category.all": "所有诊所",
    "search.category.gp_specialist": "全科与专科护理",
    "search.category.dental": "牙科护理",
    "search.category.therapy_rehab": "治疗与康复",
    "search.category.mental_wellness": "心理健康",
    "search.category.traditional_medicine": "传统医学",

    // GP, TCM, Wellness page titles
    "gpClinics.title": "预约全科医生",
    "gpClinics.subtitle": "查找您附近值得信赖的全科医生，实时可用性和数字排队管理。",
    "tcmClinics.title": "查找值得信赖的中医诊所",
    "tcmClinics.subtitle": "发现经验丰富的中医执业者，提供针灸、草药和整体护理。",
    "wellnessClinics.title": "健康与养生服务",
    "wellnessClinics.subtitle": "探索健康中心、水疗和整体健康服务，支持您的健康之旅。",

    // ContinuityServices
    "continuity.explore": "探索",

    // ClinicCard queue link
    "clinicCard.saveQueueLink": "保存排队链接",
    "clinicCard.queueLinkCopied": "排队链接已复制！",
    "clinicCard.peopleAhead": "前面的人数",
    "clinicCard.checkInCode": "签到码",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "zh" ? "zh" : "en") as Language;
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
